// Banco de fotos REALES y locales para las portadas del blog (regla de David,
// 03-oct-2026: nada de IA ni stock extranjero). Lo usa elegir-portada.ts.
//
// - B*: fotos propias ya publicadas en el sitio (barrios, obras, oficina, equipo).
// - H*: fotos de propiedades de la cartera, copiadas a /images/blog/banco/.
//   Van SIN dirección: la descripción nombra el barrio, nunca la casa.
// - W*: fotos de medios locales con acuerdo (InfoFunes, El Occidental) o de
//   licencia libre; SIEMPRE con crédito, que se muestra al pie de la nota.
//
// Para sumar una foto: copiarla a /public/images/blog/banco/ y agregar la
// entrada con una descripción concreta de qué se ve (Claude elige por eso).

export interface FotoBanco {
  id: string
  src: string // path de /public o URL absoluta
  descripcion: string
  tags: string[]
  credito?: string // "Foto: InfoFunes"; vacío = propia
}

export const BANCO_FOTOS: FotoBanco[] = [
  { id: "B1", src: "/barrios/aguadas/01.webp", descripcion: "Aérea de Aguadas (Funes): calle central con casas modernas y piletas", tags: ["barrio cerrado", "Funes", "aérea", "casas"] },
  { id: "B2", src: "/barrios/aguadas/02.webp", descripcion: "Aguadas: club house y pileta junto a la autopista", tags: ["barrio cerrado", "Funes", "amenities", "pileta"] },
  { id: "B4", src: "/barrios/aguadas/04.webp", descripcion: "Aguadas: canchas de tenis de polvo de ladrillo, vista cenital", tags: ["barrio cerrado", "deporte", "tenis", "Funes"] },
  { id: "B6", src: "/barrios/aguadas/06.webp", descripcion: "Aguadas completo desde el aire, con la autopista Rosario-Córdoba", tags: ["barrio cerrado", "Funes", "aérea", "autopista"] },
  { id: "B8", src: "/barrios/funes-hills-cadaques/01.webp", descripcion: "Funes Hills Cadaqués: casona del club house con pileta y tenis", tags: ["barrio cerrado", "Funes", "club house"] },
  { id: "B9", src: "/barrios/funes-hills-cadaques/02.webp", descripcion: "Funes Hills Cadaqués: aérea de casas con parque y piletas", tags: ["barrio cerrado", "Funes", "casas", "aérea"] },
  { id: "B11", src: "/barrios/funes-hills-cadaques/04.webp", descripcion: "Funes Hills: trama densa de casas vista desde arriba", tags: ["Funes", "barrio cerrado", "densidad", "aérea"] },
  { id: "B12", src: "/barrios/funes-hills-miraflores/01.webp", descripcion: "Funes Hills Miraflores: manzanas consolidadas desde el aire", tags: ["Funes", "barrio cerrado", "aérea", "valor m2"] },
  { id: "B13", src: "/barrios/funes-hills-miraflores/02.webp", descripcion: "Funes Hills Miraflores con la autopista y Funes de fondo, panorámica", tags: ["Funes", "crecimiento", "autopista", "aérea"] },
  { id: "B16", src: "/barrios/funes-hills-miraflores/05.webp", descripcion: "Funes Hills Miraflores: club house con pileta y tenis", tags: ["barrio cerrado", "Funes", "amenities"] },
  { id: "B20", src: "/barrios/funes-hills-san-marino/01.webp", descripcion: "Funes Hills San Marino: casas con parque y canchas", tags: ["barrio cerrado", "Funes", "casas"] },
  { id: "B22", src: "/barrios/funes-hills-san-marino/03.webp", descripcion: "Panorámica de Funes arbolado bajo cielo de nubes", tags: ["Funes", "paisaje", "panorámica"] },
  { id: "B24", src: "/barrios/funes-hills-san-marino/05.webp", descripcion: "San Marino (Funes): calles curvas con casas y arboleda", tags: ["barrio cerrado", "Funes", "aérea"] },
  { id: "B28", src: "/barrios/funes-lakes/01.webp", descripcion: "Funes Lakes: canal navegable con cielo azul", tags: ["Funes", "laguna", "barrio náutico"] },
  { id: "B30", src: "/barrios/funes-lakes/03.webp", descripcion: "Funes Lakes: loteo de canales desde el aire", tags: ["Funes", "lotes", "laguna", "aérea", "loteo"] },
  { id: "B33", src: "/barrios/funes-lakes/06.webp", descripcion: "Funes Lakes: lotes sobre canales en desarrollo", tags: ["Funes", "lotes", "loteo", "desarrollo"] },
  { id: "B34", src: "/barrios/funes-lakes/07.webp", descripcion: "Funes Lakes: club house moderno de madera y vidrio", tags: ["Funes", "amenities", "arquitectura"] },
  { id: "B36", src: "/barrios/haras-de-funes/01.webp", descripcion: "Haras de Funes: casas dispersas en lotes grandes", tags: ["Funes", "lotes grandes", "casas de campo"] },
  { id: "B37", src: "/barrios/haras-de-funes/02.webp", descripcion: "Haras de Funes: casa moderna frente a la laguna", tags: ["Funes", "laguna", "casa"] },
  { id: "B40", src: "/barrios/haras-de-funes/05.webp", descripcion: "Haras de Funes en el campo, vista aérea del loteo", tags: ["Funes", "loteo", "campo", "aérea"] },
  { id: "B42", src: "/barrios/haras-de-funes/07.webp", descripcion: "Haras de Funes: carteles de calles con nombres de caballos", tags: ["Funes", "barrio", "señalética"] },
  { id: "B44", src: "/barrios/kentucky/01.webp", descripcion: "Kentucky (Funes): barrio arbolado desde el aire", tags: ["Funes", "barrio cerrado", "arboleda", "aérea"] },
  { id: "B47", src: "/barrios/kentucky/04.webp", descripcion: "Kentucky: avenida central y casas, aérea alta", tags: ["Funes", "barrio cerrado", "aérea"] },
  { id: "B48", src: "/barrios/kentucky/05.webp", descripcion: "Kentucky: lagunas y golf desde el aire", tags: ["Funes", "golf", "laguna"] },
  { id: "B52", src: "/barrios/la-finca-1/01.webp", descripcion: "La Finca (Roldán): canchas de tenis y club house", tags: ["Roldán", "amenities", "tenis"] },
  { id: "B53", src: "/barrios/la-finca-1/02.webp", descripcion: "La Finca: club house de piedra y madera", tags: ["Roldán", "club house", "arquitectura"] },
  { id: "B55", src: "/barrios/la-finca-1/04.webp", descripcion: "La Finca: cancha de pádel al sol", tags: ["deporte", "pádel", "Roldán"] },
  { id: "B56", src: "/barrios/la-finca-1/05.webp", descripcion: "La Finca: salón comedor del club house", tags: ["Roldán", "amenities", "interior"] },
  { id: "B57", src: "/barrios/la-finca-1/06.webp", descripcion: "Living con hogar a leña y ventanales al campo (La Finca)", tags: ["hogar", "invierno", "calefacción", "interior"] },
  { id: "B58", src: "/barrios/la-finca-1/07.webp", descripcion: "Galería techada de madera del club house de La Finca", tags: ["Roldán", "galería", "arquitectura"] },
  { id: "B59", src: "/barrios/la-finca-1/08.webp", descripcion: "La Finca: loteo con laguna y casas nuevas desde el aire", tags: ["Roldán", "loteo", "aérea"] },
  { id: "B62", src: "/barrios/la-finca-2/02.webp", descripcion: "La Finca 2: calles abiertas y lotes nuevos sobre el campo", tags: ["Roldán", "loteo", "lotes", "desarrollo"] },
  { id: "B64", src: "/barrios/la-finca-2/04.webp", descripcion: "La Finca 2: loteo en el campo de Roldán, aérea", tags: ["Roldán", "lotes", "inversión"] },
  { id: "B67", src: "/barrios/san-sebastian/01.webp", descripcion: "San Sebastián (Funes): manzanas con casas, verde y canchas", tags: ["Funes", "barrio cerrado", "aérea"] },
  { id: "B68", src: "/barrios/san-sebastian/02.webp", descripcion: "San Sebastián: rotonda arbolada y casas desde arriba", tags: ["Funes", "barrio cerrado", "urbanismo"] },
  { id: "B70", src: "/barrios/san-sebastian/04.webp", descripcion: "San Sebastián: pileta del club en el parque", tags: ["Funes", "amenities", "pileta"] },
  { id: "B72", src: "/barrios/san-sebastian/06.webp", descripcion: "San Sebastián completo con la ruta, aérea", tags: ["Funes", "barrio cerrado", "aérea"] },
  { id: "B76", src: "/barrios/vida-barrio-cerrado/01.webp", descripcion: "Vida (Roldán): club house cubierto de verde", tags: ["Roldán", "arquitectura", "amenities"] },
  { id: "B78", src: "/barrios/vida-barrio-cerrado/03.webp", descripcion: "Vida barrio cerrado: pileta larga entre pastizales", tags: ["Roldán", "pileta", "amenities"] },
  { id: "B79", src: "/barrios/vida-barrio-cerrado/04.webp", descripcion: "Vida: laguna con cielo despejado", tags: ["Roldán", "laguna", "paisaje"] },
  { id: "B82", src: "/barrios/vida-barrio-cerrado/07.webp", descripcion: "Cancha de tenis de polvo de ladrillo en Vida", tags: ["deporte", "tenis", "Roldán"] },
  { id: "B84", src: "/barrios/vida-barrio-cerrado/09.webp", descripcion: "Plaza de juegos para chicos en Vida", tags: ["familias", "chicos", "plaza"] },
  { id: "B85", src: "/barrios/vida-barrio-cerrado/10.webp", descripcion: "Vecina paseando a su perro en el parque de Vida", tags: ["gente", "vida en barrio", "mascotas"] },
  { id: "B87", src: "/barrios/vida-club-de-campo/01.webp", descripcion: "Vida Club de Campo: club house octogonal desde el aire", tags: ["Roldán", "arquitectura", "amenities"] },
  { id: "B94", src: "/barrios/vida-club-de-campo/08.webp", descripcion: "Vida Club de Campo: ingreso y primeras casas, aérea", tags: ["Roldán", "loteo", "desarrollo"] },
  { id: "B96", src: "/barrios/vida-club-de-campo/10.webp", descripcion: "Vida Club de Campo: lotes con casas en construcción", tags: ["Roldán", "construcción", "lotes"] },
  { id: "B108", src: "/barrios/vida-club-de-campo/portal-ingreso-aereo.jpg", descripcion: "Portal de ingreso de Vida Club de Campo, aérea", tags: ["Roldán", "seguridad", "ingreso"] },
  { id: "B112", src: "/barrios/vida-green/01.webp", descripcion: "Vida Green: loteo nuevo en forma de triángulo, aérea", tags: ["Roldán", "loteo", "lotes"] },
  { id: "B114", src: "/barrios/vida-green/03.webp", descripcion: "Vida Green: calles trazadas sobre el campo", tags: ["Roldán", "lotes", "desarrollo"] },
  { id: "B117", src: "/barrios/vida-green/06.webp", descripcion: "Calle de acceso a Vida con cielo de nubes", tags: ["Roldán", "acceso", "calle"] },
  { id: "B119", src: "/barrios/vida-jardin/01.webp", descripcion: "Vida Jardín: portal de ingreso y guardia, aérea", tags: ["seguridad", "ingreso", "barrio cerrado", "Roldán"] },
  { id: "B120", src: "/barrios/vida-jardin/02.webp", descripcion: "Vida Jardín junto a la autopista y Funes, aérea", tags: ["Roldán", "autopista", "crecimiento"] },
  { id: "B121", src: "/barrios/vida-jardin/03.webp", descripcion: "Vida Jardín y la autopista Rosario-Córdoba, aérea", tags: ["Roldán", "autopista", "infraestructura vial"] },
  { id: "B123", src: "/barrios/vida-jardin/05.webp", descripcion: "Autopista Rosario-Córdoba con Funes y Roldán, aérea", tags: ["infraestructura vial", "autopista", "corredor oeste"] },
  { id: "B124", src: "/barrios/vida-jardin/06.webp", descripcion: "Ingreso de Vida Jardín con techo verde", tags: ["Roldán", "ingreso", "arquitectura"] },
  { id: "B127", src: "/barrios/vida-lagoon/01.webp", descripcion: "Vida Lagoon: playa y laguna cristalina", tags: ["Roldán", "laguna", "amenities"] },
  { id: "B129", src: "/barrios/vida-lagoon/03.webp", descripcion: "Laguna cristalina de Vida Lagoon", tags: ["Roldán", "laguna"] },
  { id: "B131", src: "/barrios/vida-lagoon/05.webp", descripcion: "Vida Lagoon al atardecer desde el aire", tags: ["Roldán", "laguna", "atardecer"] },
  { id: "B133", src: "/barrios/vida-lagoon/07.webp", descripcion: "Playa con palmeras y reposeras en Vida Lagoon", tags: ["Roldán", "laguna", "verano"] },
  { id: "B136", src: "/como-trabajamos/cadaques-fachada.webp", descripcion: "Fachada de casa moderna con palmeras en Cadaqués (Funes)", tags: ["casa", "Funes", "arquitectura", "venta"] },
  { id: "B137", src: "/como-trabajamos/cadaques-pileta.webp", descripcion: "Casa con pileta y jardín en Cadaqués", tags: ["casa", "pileta", "Funes"] },
  { id: "B138", src: "/como-trabajamos/cadaques-quincho.webp", descripcion: "Quincho con parrilla y barra en una casa de Cadaqués", tags: ["quincho", "parrilla", "asado"] },
  { id: "B139", src: "/como-trabajamos/cartel-4-lotes-funes.webp", descripcion: "Cartel de SI INMOBILIARIA: 4 lotes en venta en Funes", tags: ["venta", "cartel", "lotes", "precio"] },
  { id: "B141", src: "/como-trabajamos/cartel-marca-acceso-funes.webp", descripcion: "Cartel de SI INMOBILIARIA en el acceso a Funes", tags: ["marca", "Funes", "acceso"] },
  { id: "B142", src: "/como-trabajamos/cartel-obra-dockgarden.webp", descripcion: "Cartel de obra de Dock Garden al atardecer", tags: ["emprendimiento", "obra", "pozo", "Fisherton"] },
  { id: "B144", src: "/como-trabajamos/castillo-roldan.webp", descripcion: "Castillo cubierto de enredadera en Roldán", tags: ["Roldán", "historia", "patrimonio"] },
  { id: "B145", src: "/como-trabajamos/charla-colegas-rodaje.webp", descripcion: "Grabación de una charla entre colegas en la oficina", tags: ["equipo", "oficina", "asesoramiento"] },
  { id: "B146", src: "/como-trabajamos/drone-casa-aldea-golf.webp", descripcion: "Casa en Aldea Golf desde el drone", tags: ["casa", "aérea", "tasación"] },
  { id: "B147", src: "/como-trabajamos/drone-casa-kentucky.webp", descripcion: "Casa con pileta en Kentucky desde el drone", tags: ["casa", "pileta", "Funes"] },
  { id: "B148", src: "/como-trabajamos/drone-golf-funes.webp", descripcion: "Golf de Funes desde el aire", tags: ["Funes", "golf", "paisaje"] },
  { id: "B149", src: "/como-trabajamos/encuentro-colegas.webp", descripcion: "Equipo de SI INMOBILIARIA reunido en un club house", tags: ["equipo", "gente", "colegas"] },
  { id: "B151", src: "/como-trabajamos/hilo/mercado.webp", descripcion: "HILO, el sistema de SI: mercado por barrio con precios por m2", tags: ["datos", "mercado", "tasación", "ACM"] },
  { id: "B152", src: "/como-trabajamos/hilo/tasacion.webp", descripcion: "HILO: pantalla de nueva tasación", tags: ["tasación", "datos", "herramientas"] },
  { id: "B154", src: "/como-trabajamos/kentucky-pileta.webp", descripcion: "Casa con pileta en Kentucky lista para vender", tags: ["casa", "pileta", "venta", "Funes"] },
  { id: "B157", src: "/como-trabajamos/muro/02.webp", descripcion: "Casa de ladrillo visto con techo de tejas en Roldán", tags: ["ladrillo", "casa", "Roldán"] },
  { id: "B158", src: "/como-trabajamos/muro/03.webp", descripcion: "Fachada con enredadera en Roldán", tags: ["casa antigua", "Roldán"] },
  { id: "B159", src: "/como-trabajamos/muro/04.webp", descripcion: "Casas con pileta en barrio abierto, aérea", tags: ["Funes", "barrio abierto", "casas"] },
  { id: "B160", src: "/como-trabajamos/muro/08.webp", descripcion: "Casa antigua de fachada simple", tags: ["casa", "usada"] },
  { id: "B161", src: "/como-trabajamos/muro/10.webp", descripcion: "Casa blanca moderna con jardín", tags: ["casa", "moderna", "venta"] },
  { id: "B162", src: "/como-trabajamos/muro/11.webp", descripcion: "Casa moderna con palmeras", tags: ["casa", "moderna", "Funes"] },
  { id: "B163", src: "/como-trabajamos/muro/16.webp", descripcion: "Casa con camino de entrada y palmera", tags: ["casa", "Funes", "venta"] },
  { id: "B164", src: "/como-trabajamos/muro/18.webp", descripcion: "Casa con cochera doble y jardín", tags: ["casa", "cochera", "Funes"] },
  { id: "B165", src: "/como-trabajamos/oficina/fachada.webp", descripcion: "Fachada de la oficina de SI INMOBILIARIA en Funes", tags: ["oficina", "marca", "Funes"] },
  { id: "B166", src: "/como-trabajamos/oficina/sala-equipo.webp", descripcion: "Sala de trabajo del equipo en la oficina", tags: ["oficina", "equipo", "reunión"] },
  { id: "B167", src: "/como-trabajamos/oficina/sala-reuniones.webp", descripcion: "Sala de reuniones de la oficina", tags: ["oficina", "reunión", "firma", "negociación"] },
  { id: "B173", src: "/como-trabajamos/puerto-roldan-jardin.webp", descripcion: "Jardín con pileta en Puerto Roldán", tags: ["pileta", "jardín", "Roldán"] },
  { id: "B174", src: "/como-trabajamos/puerto-roldan-living.webp", descripcion: "Living luminoso de una casa en Puerto Roldán", tags: ["interior", "living", "Roldán"] },
  { id: "B175", src: "/como-trabajamos/quinquela-balcon-rio.webp", descripcion: "Balcón con vista al río Paraná en Rosario", tags: ["Rosario", "río", "departamento"] },
  { id: "B176", src: "/como-trabajamos/reunion-colegas.webp", descripcion: "Reunión del equipo en la oficina", tags: ["equipo", "reunión", "gente"] },
  { id: "B177", src: "/como-trabajamos/ruta9-aerea-cenital.webp", descripcion: "Barrio sobre Ruta 9 desde arriba, cenital", tags: ["Funes", "Ruta 9", "aérea"] },
  { id: "B178", src: "/como-trabajamos/san-sebastian-pileta.webp", descripcion: "Casa con pileta en San Sebastián", tags: ["pileta", "casa", "Funes"] },
  { id: "B179", src: "/como-trabajamos/vendidas/casa-funes-city.webp", descripcion: "Casa vendida en Funes City", tags: ["casa", "venta", "usada", "Funes"] },
  { id: "B180", src: "/como-trabajamos/vendidas/casa-funes-lakes-3-dorm.webp", descripcion: "Casa vendida en Funes Lakes, 3 dormitorios", tags: ["casa", "venta", "Funes"] },
  { id: "B181", src: "/como-trabajamos/vendidas/casa-funes-saldias.webp", descripcion: "Casa vendida en Funes, barrio Saldías", tags: ["casa", "venta", "Funes"] },
  { id: "B182", src: "/como-trabajamos/vendidas/casa-pileta-cotos-de-la-alameda.webp", descripcion: "Casa con pileta en Cotos de la Alameda (Roldán)", tags: ["casa", "pileta", "Roldán"] },
  { id: "B183", src: "/como-trabajamos/vendidas/casa-san-sebastian-3-dorm.webp", descripcion: "Casa vendida en San Sebastián, 3 dormitorios", tags: ["casa", "venta", "Funes"] },
  { id: "B184", src: "/como-trabajamos/vendidas/casa-san-sebastian-4-dorm.webp", descripcion: "Casa vendida en San Sebastián, 4 dormitorios", tags: ["casa", "venta", "Funes"] },
  { id: "B185", src: "/como-trabajamos/vendidas/depto-tierra-nueva-fisherton.webp", descripcion: "Edificio Tierra Nueva en Fisherton desde el aire", tags: ["departamentos", "Fisherton", "pozo"] },
  { id: "B186", src: "/como-trabajamos/vendidas/lote-funes-lakes-laguna.webp", descripcion: "Lote frente a la laguna en Funes Lakes", tags: ["lote", "laguna", "Funes"] },
  { id: "B188", src: "/como-trabajamos/vendidas/lote-vida-jardin.webp", descripcion: "Lotes de Vida Jardín junto a la autopista", tags: ["lotes", "Roldán", "inversión"] },
  { id: "B189", src: "/como-trabajamos/vendidas/lotes-vida-club-de-campo.webp", descripcion: "Lotes vendidos en Vida Club de Campo", tags: ["lotes", "Roldán"] },
  { id: "B190", src: "/como-trabajamos/vendidas/lotes-vida-lagoon.webp", descripcion: "Laguna de Vida Lagoon desde el drone", tags: ["laguna", "Roldán", "lotes"] },
  { id: "B191", src: "/como-trabajamos/vida-galeria.webp", descripcion: "Galería de casa nueva en Vida", tags: ["casa", "galería", "Roldán"] },
  { id: "B192", src: "/como-trabajamos/vida-pileta.webp", descripcion: "Casa con pileta en Vida", tags: ["casa", "pileta", "Roldán"] },
  { id: "B196", src: "/como-trabajamos/video/portada-drone.webp", descripcion: "Canales y lotes de Funes Lakes desde el drone", tags: ["Funes", "lotes", "laguna"] },
  { id: "B198", src: "/emprendimientos/fincazul/actual-1.jpg", descripcion: "Fincazul: terreno de obra en Funes", tags: ["obra", "emprendimiento", "Funes"] },
  { id: "B203", src: "/emprendimientos/fincazul/obra-1.jpg", descripcion: "Obra de Fincazul: cartel y obrador", tags: ["obra", "construcción", "constructora"] },
  { id: "B204", src: "/emprendimientos/fincazul/obra-2.jpg", descripcion: "Obreros con casco armando hierros en la obra de Fincazul", tags: ["obra", "construcción", "mano de obra", "costos"] },
  { id: "B205", src: "/emprendimientos/fincazul/obra-3.jpg", descripcion: "Obra de Fincazul: obrero sobre el terreno", tags: ["obra", "construcción"] },
  { id: "B206", src: "/emprendimientos/fincazul/obra-4.jpg", descripcion: "Manos atando hierros en la obra de Fincazul", tags: ["obra", "construcción", "materiales"] },
  { id: "B207", src: "/emprendimientos/fincazul/obra-5.jpg", descripcion: "Obreros armando la estructura en Fincazul", tags: ["obra", "construcción", "mano de obra"] },
  { id: "B208", src: "/emprendimientos/fincazul/obra-6.jpg", descripcion: "Hierros de fundación en el terreno de Fincazul", tags: ["obra", "materiales", "cimientos"] },
  { id: "B248", src: "/images/sedes/funes.webp", descripcion: "Sede de SI INMOBILIARIA en Funes", tags: ["oficina", "marca", "Funes"] },
  { id: "B249", src: "/images/sedes/historica.webp", descripcion: "La oficina histórica de Susana Ippoliti en Roldán", tags: ["historia", "Roldán", "oficina", "trayectoria"] },
  { id: "B250", src: "/images/sedes/ventas.webp", descripcion: "Local de ventas de SI INMOBILIARIA con vidriera", tags: ["oficina", "local comercial"] },
  { id: "B255", src: "/images/distrito-roldan/hero-aerea.webp", descripcion: "Distrito Roldán: loteo en el casco urbano, aérea", tags: ["Roldán", "loteo", "lotes", "desarrollo"] },
  { id: "B256", src: "/images/distrito-roldan/obra-5.webp", descripcion: "Obras de Distrito Roldán desde el aire", tags: ["Roldán", "obra", "loteo"] },
  { id: "B257", src: "/images/distrito-roldan/obra-6.webp", descripcion: "Distrito Roldán: calles nuevas y lotes, aérea", tags: ["Roldán", "obra", "lotes"] },
  { id: "B260", src: "/images/distrito-roldan/obra-9.webp", descripcion: "Máquina abriendo calle en Distrito Roldán, cenital", tags: ["obra", "infraestructura", "Roldán"] },
  { id: "B263", src: "/images/dockgarden/aerea-fisherton.webp", descripcion: "Fisherton y el golf desde el aire", tags: ["Fisherton", "Rosario", "aérea"] },
  { id: "B271", src: "/images/dockgarden/obra-2026-09/01.webp", descripcion: "Dock Garden en obra, aérea con el barrio", tags: ["obra", "pozo", "Fisherton", "emprendimiento"] },
  { id: "B272", src: "/images/dockgarden/obra-2026-09/02.webp", descripcion: "Dock Garden: estructura en obra, cenital", tags: ["obra", "pozo", "emprendimiento"] },
  { id: "B273", src: "/images/dockgarden/obra-2026-09/03.webp", descripcion: "Interior de Dock Garden en obra con muros de ladrillo", tags: ["obra", "pozo", "ladrillo"] },
  { id: "B274", src: "/images/dockgarden/obra-2026-09/04.webp", descripcion: "Losa de hormigón y estructura en Dock Garden", tags: ["obra", "construcción tradicional", "hormigón"] },
  { id: "B275", src: "/images/dockgarden/obra-2026-09/05.webp", descripcion: "Planta libre en obra con vista verde (Dock Garden)", tags: ["obra", "pozo", "departamento"] },
  { id: "B276", src: "/images/dockgarden/obra-2026-09/06.webp", descripcion: "Departamento en obra, ventanales al golf", tags: ["obra", "pozo", "departamento"] },
  { id: "B277", src: "/images/dockgarden/obra-2026-09/07.webp", descripcion: "Obra gruesa terminada con vista al verde", tags: ["obra", "pozo", "avance"] },
  { id: "B307", src: "/nosotros/si-inmobiliaria-oficina-funes-interior.webp", descripcion: "Interior de la oficina de SI INMOBILIARIA en Funes, con obras de arte", tags: ["oficina", "arte", "galería"] },
  { id: "B308", src: "/blog/images/funes-autopista-acceso-aerea.webp", descripcion: "Acceso a Funes y la autopista desde el aire", tags: ["Funes", "autopista", "acceso"] },
  { id: "B309", src: "/blog/images/funes-avenida-arbolada-campo.webp", descripcion: "Avenida arbolada de Funes y el campo, aérea", tags: ["Funes", "arboleda", "paisaje"] },
  { id: "B311", src: "/blog/images/funes-barrios-arbolados-aerea.webp", descripcion: "Funes: barrios arbolados desde el aire", tags: ["Funes", "barrios", "aérea"] },
  { id: "B312", src: "/blog/images/funes-barrios-nuevos-aereo.webp", descripcion: "Funes: barrios nuevos desde el aire", tags: ["Funes", "barrios nuevos", "crecimiento"] },
  { id: "B313", src: "/blog/images/funes-casas-piletas-barrios-aereo.webp", descripcion: "Funes: casas con pileta, vista aérea", tags: ["Funes", "casas", "pileta"] },
  { id: "B314", src: "/blog/images/funes-roldan-zona-oeste-aerea.webp", descripcion: "Funes y Roldán, zona oeste desde el aire", tags: ["corredor oeste", "Funes", "Roldán"] },
  { id: "B315", src: "/blog/images/funes-vista-aerea-barrios-2026.webp", descripcion: "Funes 2026 desde el aire", tags: ["Funes", "aérea", "mercado"] },
  { id: "B316", src: "/blog/images/funes-zona-residencial-arboles-aereo.webp", descripcion: "Zona residencial arbolada de Funes, aérea", tags: ["Funes", "residencial"] },
  { id: "B317", src: "/blog/images/roldan-vista-aerea-autopista.webp", descripcion: "Roldán y la autopista desde el aire", tags: ["Roldán", "autopista", "mudanza"] },
  { id: "B318", src: "/blog/images/roldan-vista-aerea-panoramica.webp", descripcion: "Roldán, vista aérea panorámica", tags: ["Roldán", "ciudad", "crecimiento"] },
  { id: "B322", src: "/familia-flores.webp", descripcion: "La familia fundadora de SI INMOBILIARIA en la oficina", tags: ["familia", "historia", "trayectoria"] },
  { id: "B324", src: "/hero-barrios.webp", descripcion: "Barrios cerrados de Funes con lagunas, aérea", tags: ["Funes", "barrios cerrados"] },
  { id: "B327", src: "/oficina-funes.webp", descripcion: "Oficina de SI INMOBILIARIA en Funes", tags: ["oficina", "marca", "Funes"] },
  { id: "B328", src: "/oficina-historica.webp", descripcion: "Oficina histórica Susana Ippoliti en Roldán", tags: ["historia", "Roldán"] },
  { id: "B329", src: "/oficina-ruta9.webp", descripcion: "Oficina de Ruta 9 con vidriera de propiedades", tags: ["oficina", "Roldán", "vidriera"] },
  { id: "H4", src: "/images/blog/banco/cartera-casa-moderna-con-galeria-y-jardin-en-un-country-de.webp", descripcion: "Casa moderna con galería y jardín en un country de Funes", tags: ["casa", "Funes", "moderna"] },
  { id: "H5", src: "/images/blog/banco/cartera-casa-blanca-moderna-con-jardin-en-kentucky-funes.webp", descripcion: "Casa blanca moderna con jardín en Kentucky (Funes)", tags: ["casa", "Funes", "moderna", "crédito"] },
  { id: "H7", src: "/images/blog/banco/cartera-casa-moderna-de-dos-plantas-en-funes.webp", descripcion: "Casa moderna de dos plantas en Funes", tags: ["casa", "Funes", "crédito", "compra"] },
  { id: "H8", src: "/images/blog/banco/cartera-casa-moderna-con-palmeras-en-funes.webp", descripcion: "Casa moderna con palmeras en Funes", tags: ["casa", "Funes", "compra"] },
  { id: "H9", src: "/images/blog/banco/cartera-casa-frente-a-la-laguna-en-funes-lakes.webp", descripcion: "Casa frente a la laguna en Funes Lakes", tags: ["casa", "laguna", "Funes", "compra"] },
  { id: "H10", src: "/images/blog/banco/cartera-edificio-de-departamentos-en-funes.webp", descripcion: "Edificio de departamentos en Funes", tags: ["departamentos", "Funes", "inversión", "renta"] },
  { id: "H12", src: "/images/blog/banco/cartera-casa-con-cochera-y-autos-en-barrio-cerrado-de-fune.webp", descripcion: "Casa con cochera y autos en barrio cerrado de Funes", tags: ["casa", "Funes", "barrio cerrado"] },
  { id: "H16", src: "/images/blog/banco/cartera-casa-de-ladrillo-de-dos-plantas-en-funes.webp", descripcion: "Casa de ladrillo de dos plantas en Funes", tags: ["casa", "ladrillo", "Funes"] },
  { id: "H17", src: "/images/blog/banco/cartera-casa-en-roldan-con-cartel-de-alquiler.webp", descripcion: "Casa en Roldán con cartel de alquiler", tags: ["alquiler", "casa", "Roldán"] },
  { id: "H18", src: "/images/blog/banco/cartera-casa-en-barrio-las-tardes-de-roldan.webp", descripcion: "Casa en barrio Las Tardes de Roldán", tags: ["casa", "Roldán", "valuación"] },
  { id: "H21", src: "/images/blog/banco/cartera-galpon-en-el-area-industrial-de-roldan.webp", descripcion: "Galpón en el área industrial de Roldán", tags: ["industria", "empleo", "galpón", "Roldán"] },
  { id: "H23", src: "/images/blog/banco/cartera-casa-con-techo-de-tejas-entre-arboles-en-funes.webp", descripcion: "Casa con techo de tejas entre árboles en Funes", tags: ["casa", "Funes", "invierno", "jardín"] },
  { id: "H27", src: "/images/blog/banco/cartera-cocina-moderna-de-un-departamento-en-funes.webp", descripcion: "Cocina moderna de un departamento en Funes", tags: ["cocina", "interior", "gas"] },
  { id: "H33", src: "/images/blog/banco/cartera-casa-de-piedra-en-el-centro-de-roldan.webp", descripcion: "Casa de piedra en el centro de Roldán", tags: ["casa", "Roldán", "usada", "humedad"] },
  { id: "H35", src: "/images/blog/banco/cartera-casa-moderna-con-cochera-en-funes.webp", descripcion: "Casa moderna con cochera en Funes", tags: ["casa", "Funes", "hipoteca"] },
  { id: "H43", src: "/images/blog/banco/cartera-casa-con-palmeras-en-san-sebastian-funes.webp", descripcion: "Casa con palmeras en San Sebastián (Funes)", tags: ["casa", "Funes", "barrio cerrado"] },
  { id: "H57", src: "/images/blog/banco/cartera-casa-con-jardin-en-cotos-de-la-alameda-roldan.webp", descripcion: "Casa con jardín en Cotos de la Alameda (Roldán)", tags: ["casa", "jardín", "Roldán"] },
  { id: "H60", src: "/images/blog/banco/cartera-casa-moderna-de-hormigon-en-funes.webp", descripcion: "Casa moderna de hormigón en Funes", tags: ["casa", "Funes", "crédito"] },
  { id: "H64", src: "/images/blog/banco/cartera-distrito-roldan-lotes-nuevos-desde-el-aire.webp", descripcion: "Distrito Roldán: lotes nuevos desde el aire", tags: ["lotes", "Roldán", "valor del lote"] },
  { id: "H71", src: "/images/blog/banco/cartera-casa-en-tierra-de-suenos-1-roldan.webp", descripcion: "Casa en Tierra de Sueños 1 (Roldán)", tags: ["casa", "Roldán", "Tierra de Sueños"] },
  { id: "H78", src: "/images/blog/banco/cartera-casa-con-pileta-en-las-acequias-roldan.webp", descripcion: "Casa con pileta en Las Acequias (Roldán)", tags: ["casa", "pileta", "Roldán"] },
  { id: "H90", src: "/images/blog/banco/cartera-casa-de-ladrillo-con-jardin-en-funes.webp", descripcion: "Casa de ladrillo con jardín en Funes", tags: ["casa", "ladrillo", "Funes"] },
  { id: "H99", src: "/images/blog/banco/cartera-casa-nueva-en-vida-club-de-campo.webp", descripcion: "Casa nueva en Vida Club de Campo", tags: ["casa", "Roldán", "sustentable", "nueva"] },
  { id: "H119", src: "/images/blog/banco/cartera-casa-moderna-con-jardin-en-barrio-vida-funes.webp", descripcion: "Casa moderna con jardín en barrio Vida (Funes)", tags: ["casa", "Funes", "moderna"] },
  { id: "H127", src: "/images/blog/banco/cartera-casa-entre-arboles-sin-hojas-en-roldan-invierno.webp", descripcion: "Casa entre árboles sin hojas en Roldán, invierno", tags: ["casa", "Roldán", "invierno", "aislación"] },
  { id: "H129", src: "/images/blog/banco/cartera-casa-en-aldea-fisherton-desde-el-drone.webp", descripcion: "Casa en Aldea Fisherton desde el drone", tags: ["casa", "Fisherton", "aérea"] },
  { id: "H147", src: "/images/blog/banco/cartera-barrio-acequias-del-aire-en-roldan-aerea-de-casas.webp", descripcion: "Barrio Acequias del Aire en Roldán, aérea de casas", tags: ["Roldán", "barrio", "casas", "aérea"] },
  { id: "H159", src: "/images/blog/banco/cartera-local-en-roldan-con-cartel-de-alquiler-de-si-inmob.webp", descripcion: "Local en Roldán con cartel de alquiler de SI INMOBILIARIA", tags: ["alquiler", "local comercial", "Roldán"] },
  { id: "H186", src: "/images/blog/banco/cartera-casa-en-las-tardes-roldan-con-galeria.webp", descripcion: "Casa en Las Tardes (Roldán) con galería", tags: ["casa", "Roldán", "crédito"] },
  { id: "H190", src: "/images/blog/banco/cartera-casa-de-dos-plantas-en-puerto-roldan.webp", descripcion: "Casa de dos plantas en Puerto Roldán", tags: ["casa", "Roldán", "crédito"] },
  { id: "H191", src: "/images/blog/banco/cartera-departamento-en-rosario-con-cartel-de-alquiler-de.webp", descripcion: "Departamento en Rosario con cartel de alquiler de SI INMOBILIARIA", tags: ["alquiler", "departamento", "Rosario"] },
  { id: "H225", src: "/images/blog/banco/cartera-interior-moderno-de-un-departamento-en-pichincha-r.webp", descripcion: "Interior moderno de un departamento en Pichincha (Rosario)", tags: ["interior", "departamento", "domótica"] },
  { id: "H228", src: "/images/blog/banco/cartera-casa-en-barrio-abierto-de-las-tardes-roldan.webp", descripcion: "Casa en barrio abierto de Las Tardes (Roldán)", tags: ["casa", "Roldán", "alquilar o comprar"] },
  { id: "H241", src: "/images/blog/banco/cartera-living-comedor-con-escalera-en-una-casa-de-roldan.webp", descripcion: "Living comedor con escalera en una casa de Roldán", tags: ["interior", "living", "Roldán"] },
  { id: "H243", src: "/images/blog/banco/cartera-casa-con-palmera-en-aguadas-funes.webp", descripcion: "Casa con palmera en Aguadas (Funes)", tags: ["casa", "Funes", "crédito"] },
  { id: "H254", src: "/images/blog/banco/cartera-casas-con-pileta-en-cotos-de-la-alameda-roldan-aer.webp", descripcion: "Casas con pileta en Cotos de la Alameda (Roldán), aérea", tags: ["casas", "Roldán", "aérea"] },
  { id: "W1", src: "/images/blog/banco/local-fachada-del-nuevo-hospital-samco-eva-peron-de-fune.webp", descripcion: "Fachada del nuevo Hospital SAMCo Eva Perón de Funes", tags: ["vivir", "corredor", "oeste", "rosario", "servicios", "medicos"], credito: "Foto: InfoFunes" },
  { id: "W2", src: "/images/blog/banco/local-hospital-samco-eva-peron-de-funes-recien-terminado.webp", descripcion: "Hospital SAMCo Eva Perón de Funes recién terminado, ingreso y cartel de Emergencias", tags: ["vivir", "corredor", "oeste", "rosario", "servicios", "medicos"], credito: "Foto: InfoFunes" },
  { id: "W3", src: "/images/blog/banco/local-centro-de-salud-dr-abel-faust-de-funes.webp", descripcion: "Centro de Salud Dr. Abel Faust de Funes", tags: ["vivir", "corredor", "oeste", "rosario", "servicios", "medicos"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W6", src: "/images/blog/banco/local-invencible-arena-en-el-parque-independencia-de-ros.webp", descripcion: "Invencible Arena en el Parque Independencia de Rosario, vista aérea al atardecer", tags: ["juegos", "suramericanos", "2026", "rosario", "funes", "roldan"], credito: "Foto: Gobierno de Santa Fe" },
  { id: "W7", src: "/images/blog/banco/local-fachada-del-invencible-arena-de-rosario.webp", descripcion: "Fachada del Invencible Arena de Rosario", tags: ["juegos", "suramericanos", "2026", "rosario", "funes", "roldan"], credito: "Foto: Gobierno de Santa Fe" },
  { id: "W8", src: "/images/blog/banco/local-obra-del-centro-acuatico-provincial-de-rosario-ex.webp", descripcion: "Obra del Centro Acuático Provincial de Rosario (ex Batallón 121), vista aérea", tags: ["juegos", "suramericanos", "2026", "rosario", "funes", "roldan"], credito: "Foto: Gobierno de Santa Fe" },
  { id: "W9", src: "/images/blog/banco/local-obra-de-la-segunda-etapa-del-acceso-a-puerto-rolda.webp", descripcion: "Obra de la segunda etapa del acceso a Puerto Roldán / Tierra de Sueños II y III, retroexcavadora junto a la calzada", tags: ["tierra", "suenos", "roldan", "infraestructura", "servicios"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W10", src: "/images/blog/banco/local-esquina-comercial-de-tierra-de-suenos-2-av-de-las.webp", descripcion: "Esquina comercial de Tierra de Sueños 2 (Av. de las Libertades y Av. de la Paz) con el supermercado Éxito", tags: ["tierra", "suenos", "roldan", "infraestructura", "servicios"], credito: "Foto: El Occidental" },
  { id: "W11", src: "/images/blog/banco/local-obra-de-la-nueva-escuela-secundaria-n-730-en-tierr.webp", descripcion: "Obra de la nueva Escuela Secundaria N° 730 en Tierra de Sueños III", tags: ["tierra", "suenos", "roldan", "infraestructura", "servicios"], credito: "Foto: InfoFunes" },
  { id: "W16", src: "/images/blog/banco/local-vista-desde-el-hotel-sol-de-funes-hacia-el-estacio.webp", descripcion: "Vista desde el hotel Sol de Funes hacia el estacionamiento y la autopista", tags: ["hotel", "cinco", "estrellas", "funes", "mercado", "inmobiliario"], credito: "Foto: InfoFunes" },
  { id: "W17", src: "/images/blog/banco/local-habitacion-terminada-del-hotel-sol-de-funes.webp", descripcion: "Habitación terminada del hotel Sol de Funes", tags: ["hotel", "cinco", "estrellas", "funes", "impacto"], credito: "Foto: InfoFunes" },
  { id: "W19", src: "/images/blog/banco/local-excavadora-limpiando-y-rectificando-un-desague-est.webp", descripcion: "Excavadora limpiando y rectificando un desagüe estructural en Roldán", tags: ["drenaje", "roldan", "limpieza", "canales", "valor", "propiedades"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W20", src: "/images/blog/banco/local-zanjeo-de-desague-con-excavadora-en-un-barrio-de-r.webp", descripcion: "Zanjeo de desagüe con excavadora en un barrio de Roldán", tags: ["drenaje", "roldan", "limpieza", "canales", "valor", "propiedades"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W21", src: "/images/blog/banco/local-funcionarios-recorren-un-canal-estructural-en-limp.webp", descripcion: "Funcionarios recorren un canal estructural en limpieza en Roldán", tags: ["drenaje", "roldan", "limpieza", "canales", "valor", "propiedades"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W22", src: "/images/blog/banco/local-vista-aerea-del-cruce-de-ruta-9-y-a012-en-roldan-d.webp", descripcion: "Vista aérea del cruce de Ruta 9 y A012 en Roldán, donde se proyecta la rotonda", tags: ["infraestructura", "vial", "roldan", "impacto", "valor", "propiedades"], credito: "Foto: El Occidental" },
  { id: "W25", src: "/images/blog/banco/local-dos-autobombas-de-bomberos-voluntarios-de-funes-en.webp", descripcion: "Dos autobombas de Bomberos Voluntarios de Funes en servicio", tags: ["bomberos", "funes", "roldan", "infraestructura", "valor", "propiedad"], credito: "Foto: InfoFunes" },
  { id: "W26", src: "/images/blog/banco/local-cuartel-de-bomberos-voluntarios-de-funes-con-autob.webp", descripcion: "Cuartel de Bomberos Voluntarios de Funes con autobombas", tags: ["bomberos", "funes", "roldan", "infraestructura", "valor", "propiedad"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W28", src: "/images/blog/banco/local-tecnicos-de-la-epe-con-casco-en-obra-electrica-de.webp", descripcion: "Técnicos de la EPE con casco en obra eléctrica de Roldán (2021)", tags: ["infraestructura", "electrica", "roldan", "licitacion", "desarrollo", "inmobiliario"], credito: "Foto: Gobierno de Santa Fe" },
  { id: "W31", src: "/images/blog/banco/local-vista-aerea-de-un-loteo-nuevo-en-roldan.webp", descripcion: "Vista aérea de un loteo nuevo en Roldán", tags: ["roldan", "crecimiento", "demografico", "desarrollo", "inmobiliario"], credito: "Foto: El Occidental" },
  { id: "W32", src: "/images/blog/banco/local-monumento-cartel-de-ingreso-a-roldan-contraluz.webp", descripcion: "Monumento-cartel de ingreso a Roldán (contraluz)", tags: ["roldan", "crecimiento", "demografico", "desarrollo", "inmobiliario"], credito: "Foto: InfoFunes" },
  { id: "W33", src: "/images/blog/banco/local-colegio-maria-auxiliadora-de-funes.webp", descripcion: "Colegio María Auxiliadora de Funes", tags: ["colegios", "roldan", "funes", "guia", "familias", "mudan"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W34", src: "/images/blog/banco/local-colegio-joan-miro-de-funes.webp", descripcion: "Colegio Joan Miró de Funes", tags: ["colegios", "roldan", "funes", "guia", "familias", "mudan"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W35", src: "/images/blog/banco/local-obra-de-la-escuela-secundaria-n-730-de-roldan.webp", descripcion: "Obra de la Escuela Secundaria N° 730 de Roldán", tags: ["colegios", "roldan", "funes", "guia", "familias", "mudan"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W36", src: "/images/blog/banco/local-supermercado-exito-en-esquina-comercial-de-tierra.webp", descripcion: "Supermercado Éxito en esquina comercial de Tierra de Sueños 2, Roldán", tags: ["supermercados", "comercios", "roldan", "vivir", "auto"], credito: "Foto: El Occidental" },
  { id: "W38", src: "/images/blog/banco/local-colectivo-interurbano-amarillo-con-destino-roldan.webp", descripcion: "Colectivo interurbano amarillo con destino ROLDAN en el cartel", tags: ["transporte", "colectivo", "roldan", "rosario", "opciones"], credito: "Foto: InfoFunes" },
  { id: "W39", src: "/images/blog/banco/local-colectivo-monticas-circulando-por-funes.webp", descripcion: "Colectivo Monticas circulando por Funes", tags: ["transporte", "colectivo", "roldan", "rosario", "opciones"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W40", src: "/images/blog/banco/local-nueva-garita-de-colectivo-en-funes.webp", descripcion: "Nueva garita de colectivo en Funes", tags: ["transporte", "colectivo", "roldan", "rosario", "opciones"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W41", src: "/images/blog/banco/local-cerveceria-tbs-acequias-en-roldan-fachada-con-deck.webp", descripcion: "Cervecería TBS Acequias en Roldán, fachada con deck", tags: ["restaurantes", "gastronomia", "roldan", "para", "vivir", "disfrutar"], credito: "Foto: InfoFunes" },
  { id: "W42", src: "/images/blog/banco/local-container-de-rio-helados-en-el-parque-de-food-truc.webp", descripcion: "Container de Río Helados en el parque de food trucks Punto Roldán", tags: ["restaurantes", "gastronomia", "roldan", "para", "vivir", "disfrutar"], credito: "Foto: InfoFunes" },
  { id: "W43", src: "/images/blog/banco/local-fachada-del-club-sportsman-de-roldan-con-dirigente.webp", descripcion: "Fachada del Club Sportsman de Roldán con dirigentes y funcionarios", tags: ["gimnasios", "deportes", "roldan", "calidad", "vida"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W44", src: "/images/blog/banco/local-polideportivo-municipal-humberto-illia-de-funes.webp", descripcion: "Polideportivo Municipal Humberto Illia de Funes", tags: ["gimnasios", "deportes", "roldan", "calidad", "vida"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W45", src: "/images/blog/banco/local-estacion-ferroviaria-de-funes.webp", descripcion: "Estación ferroviaria de Funes", tags: ["corredor", "funes", "roldan", "historia", "crecimiento", "proyeccion"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W46", src: "/images/blog/banco/local-plaza-san-jose-funes.webp", descripcion: "Plaza San José, Funes", tags: ["corredor", "funes", "roldan", "historia", "crecimiento", "proyeccion"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W50", src: "/images/blog/banco/local-vias-y-estacion-de-funes.webp", descripcion: "Vías y estación de Funes", tags: ["funes", "roldan", "nuevo", "crecimiento", "inmobiliario", "gran"], credito: "Foto: Mweper / Wikimedia Commons, CC BY-SA 4.0" },
  { id: "W51", src: "/images/blog/banco/local-showroom-de-casas-modulares-en-tierra-de-suenos-2.webp", descripcion: "Showroom de casas modulares en Tierra de Sueños 2, Roldán (incluye cartel con precio)", tags: ["casas", "modulares", "chinas", "funes", "roldan", "20000"], credito: "Foto: El Occidental" },
  { id: "W52", src: "/images/blog/banco/local-paneles-solares-sobre-techo-de-chapa-en-funes.webp", descripcion: "Paneles solares sobre techo de chapa en Funes", tags: ["paneles", "solares", "roldan", "funes", "conviene", "2025"], credito: "Foto: InfoFunes" },
  { id: "W53", src: "/images/blog/banco/local-guardia-controlando-el-ingreso-de-un-vehiculo-a-un.webp", descripcion: "Guardia controlando el ingreso de un vehículo a un barrio privado del Gran Rosario", tags: ["seguridad", "privada", "barrios", "cerrados", "roldan", "funes"], credito: "Foto: El Occidental" },
  { id: "W54", src: "/images/blog/banco/local-camioneta-0-km-de-la-guardia-urbana-de-roldan.webp", descripcion: "Camioneta 0 km de la Guardia Urbana de Roldán", tags: ["seguridad", "privada", "barrios", "cerrados", "roldan", "funes"], credito: "Foto: Municipalidad de Roldán" },
  { id: "W55", src: "/images/blog/banco/local-totem-de-seguridad-con-camara-en-una-esquina-de-ro.webp", descripcion: "Tótem de seguridad con cámara en una esquina de Roldán", tags: ["seguridad", "privada", "barrios", "cerrados", "roldan", "funes"], credito: "Foto: El Occidental" },
]
