// AUTO-GENERADO desde OpenStreetMap (Overpass) + feed HILO — 2026-07-26
// Barrios de Funes, Roldán y Rosario para las landings de tasación.
//   ppm2Curado = USD/m² relevado A MANO por David (ago-2026): manda sobre todo.
//   ppm2       = USD/m² de TIERRA (terrenos del feed). Para casas y lotes.
//   ppm2Depto  = USD/m² CUBIERTO de departamentos comparables de la zona.
//   null       = sin muestra propia: se usa el promedio de la ciudad.
// Regenerar: ver scripts/tasador/README.md

export interface BarrioTasador {
  slug: string
  /** USD/m² relevado a mano por David (ago-2026). Pisa el promedio automático.
   *  Al REGENERAR el archivo desde OSM/feed, conservar estos campos. */
  ppm2Curado?: number
  nombre: string
  ciudad: "Funes" | "Roldán" | "Rosario"
  lat: number
  lon: number
  cerrado: boolean
  ppm2: number | null
  muestras: number
  ppm2Depto: number | null
  muestrasDepto: number
}

// Promedios por ciudad — fallback cuando el barrio no tiene muestra propia.
export const PPM2_CIUDAD: Record<string, number> = {
  "Funes": 90,
  "Roldán": 70,
  "Rosario": 400,
}

// Departamentos: USD/m² cubierto promedio por ciudad.
export const PPM2_DEPTO_CIUDAD: Record<string, number> = {
  "Funes": 2150,
  "Roldán": 1500,
  "Rosario": 2182,
}

export const BARRIOS_TASADOR: BarrioTasador[] = [
  {
    "slug": "funes",
    "nombre": "Funes",
    "ciudad": "Funes",
    "lat": -32.9206,
    "lon": -60.811,
    "cerrado": false,
    "ppm2": 176,
    "muestras": 36,
    "ppm2Depto": 2150,
    "muestrasDepto": 1
  },
  {
    "slug": "roldan",
    "nombre": "Roldán",
    "ciudad": "Roldán",
    "lat": -32.902,
    "lon": -60.913,
    "cerrado": false,
    "ppm2": 106,
    "muestras": 26,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "abra-casas-concretas",
    "nombre": "ABRA - Casas Concretas",
    "ciudad": "Funes",
    "lat": -32.93123,
    "lon": -60.83169,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "aero-funes",
    "nombre": "Aero Funes",
    "ciudad": "Funes",
    "lat": -32.92334,
    "lon": -60.77602,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "aguadas",
    "nombre": "Aguadas",
    "ciudad": "Funes",
    "lat": -32.93944,
    "lon": -60.80767,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "alfonsin",
    "nombre": "Alfonsín",
    "ciudad": "Funes",
    "lat": -32.90177,
    "lon": -60.81298,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "altos-de-funes",
    "nombre": "Altos de Funes",
    "ciudad": "Funes",
    "lat": -32.91196,
    "lon": -60.80575,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "atardeceres-de-funes",
    "nombre": "Atardeceres de Funes",
    "ciudad": "Funes",
    "lat": -32.91212,
    "lon": -60.83032,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "barani",
    "nombre": "Barani",
    "ciudad": "Funes",
    "lat": -32.92306,
    "lon": -60.77937,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "barquia-3",
    "nombre": "Barquía 3",
    "ciudad": "Funes",
    "lat": -32.91902,
    "lon": -60.81379,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "brancatelli",
    "nombre": "Brancatelli",
    "ciudad": "Funes",
    "lat": -32.92263,
    "lon": -60.84824,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "brisas-de-funes",
    "nombre": "Brisas de Funes",
    "ciudad": "Funes",
    "lat": -32.93139,
    "lon": -60.83272,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "brisas-de-funes-1",
    "nombre": "Brisas de Funes 1",
    "ciudad": "Funes",
    "lat": -32.93126,
    "lon": -60.83287,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "brisas-de-funes-2",
    "nombre": "Brisas de Funes 2",
    "ciudad": "Funes",
    "lat": -32.93164,
    "lon": -60.83285,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "brisas-de-funes-3",
    "nombre": "Brisas de Funes 3",
    "ciudad": "Funes",
    "lat": -32.93246,
    "lon": -60.83135,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "buena-vista",
    "nombre": "Buena Vista",
    "ciudad": "Funes",
    "lat": -32.92084,
    "lon": -60.81835,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cadaques",
    "ppm2Curado": 250,
    "nombre": "Cadaques",
    "ciudad": "Funes",
    "lat": -32.92733,
    "lon": -60.83195,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "calmo",
    "nombre": "Calmo",
    "ciudad": "Funes",
    "lat": -32.93837,
    "lon": -60.81507,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "candelaria",
    "nombre": "Candelaria",
    "ciudad": "Funes",
    "lat": -32.91973,
    "lon": -60.81231,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cannes",
    "nombre": "Cannes",
    "ciudad": "Funes",
    "lat": -32.90387,
    "lon": -60.79923,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cantegril",
    "ppm2Curado": 200,
    "nombre": "Cantegril",
    "ciudad": "Funes",
    "lat": -32.92732,
    "lon": -60.84566,
    "cerrado": false,
    "ppm2": 196,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cantore-linare",
    "nombre": "Cantore Linare",
    "ciudad": "Funes",
    "lat": -32.9106,
    "lon": -60.85539,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "carpanetto",
    "nombre": "Carpanetto",
    "ciudad": "Funes",
    "lat": -32.91156,
    "lon": -60.7989,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "colinas-de-funes",
    "nombre": "Colinas de Funes",
    "ciudad": "Funes",
    "lat": -32.92275,
    "lon": -60.84545,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condo-funes",
    "nombre": "Condo Funes",
    "ciudad": "Funes",
    "lat": -32.91215,
    "lon": -60.80292,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominio-las-moras",
    "nombre": "Condominio Las Moras",
    "ciudad": "Funes",
    "lat": -32.92147,
    "lon": -60.80134,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominios-bagua",
    "nombre": "Condominios Bagua",
    "ciudad": "Funes",
    "lat": -32.92096,
    "lon": -60.81631,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominios-dm",
    "nombre": "Condominios DM",
    "ciudad": "Funes",
    "lat": -32.92535,
    "lon": -60.84926,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominios-dm-2",
    "nombre": "Condominios DM 2",
    "ciudad": "Funes",
    "lat": -32.92554,
    "lon": -60.85526,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominios-pedro-rios",
    "nombre": "Condominios Pedro Ríos",
    "ciudad": "Funes",
    "lat": -32.91398,
    "lon": -60.82269,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "damfield-residencial",
    "nombre": "Damfield Residencial",
    "ciudad": "Funes",
    "lat": -32.94582,
    "lon": -60.81492,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-bosco",
    "nombre": "Don Bosco",
    "ciudad": "Funes",
    "lat": -32.90668,
    "lon": -60.80899,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-bosco-ii",
    "nombre": "Don Bosco II",
    "ciudad": "Funes",
    "lat": -32.90938,
    "lon": -60.80762,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-ignacio",
    "nombre": "Don Ignacio",
    "ciudad": "Funes",
    "lat": -32.92406,
    "lon": -60.86308,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-juan",
    "nombre": "Don Juan",
    "ciudad": "Funes",
    "lat": -32.92974,
    "lon": -60.80502,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-luis",
    "nombre": "Don Luis",
    "ciudad": "Funes",
    "lat": -32.91057,
    "lon": -60.85828,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-mateo",
    "ppm2Curado": 135,
    "nombre": "Don Mateo",
    "ciudad": "Funes",
    "lat": -32.92804,
    "lon": -60.85489,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "drazi",
    "nombre": "Drazi",
    "ciudad": "Funes",
    "lat": -32.92374,
    "lon": -60.8357,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-bosquecillo",
    "nombre": "El Bosquecillo",
    "ciudad": "Funes",
    "lat": -32.91191,
    "lon": -60.84992,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-palomar",
    "nombre": "El Palomar",
    "ciudad": "Funes",
    "lat": -32.92212,
    "lon": -60.83417,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-sol-de-funes",
    "nombre": "El Sol de Funes",
    "ciudad": "Funes",
    "lat": -32.92257,
    "lon": -60.85244,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-centro",
    "ppm2Curado": 375,
    "nombre": "Funes Centro",
    "ciudad": "Funes",
    "lat": -32.91876,
    "lon": -60.8109,
    "cerrado": false,
    "ppm2": 483,
    "muestras": 2,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-city",
    "ppm2Curado": 90,
    "nombre": "Funes City",
    "ciudad": "Funes",
    "lat": -32.90575,
    "lon": -60.79823,
    "cerrado": false,
    "ppm2": 155,
    "muestras": 2,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-green-house",
    "nombre": "Funes Green House",
    "ciudad": "Funes",
    "lat": -32.91328,
    "lon": -60.80201,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-lakes",
    "ppm2Curado": 150,
    "nombre": "Funes Lakes",
    "ciudad": "Funes",
    "lat": -32.93669,
    "lon": -60.79824,
    "cerrado": true,
    "ppm2": 187,
    "muestras": 7,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-norte",
    "nombre": "Funes Norte",
    "ciudad": "Funes",
    "lat": -32.89938,
    "lon": -60.81018,
    "cerrado": false,
    "ppm2": 118,
    "muestras": 5,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-ranch",
    "nombre": "Funes Ranch",
    "ciudad": "Funes",
    "lat": -32.91162,
    "lon": -60.85304,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-suites",
    "nombre": "Funes Suites",
    "ciudad": "Funes",
    "lat": -32.93243,
    "lon": -60.8319,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "haras-de-funes",
    "nombre": "Haras de Funes",
    "ciudad": "Funes",
    "lat": -32.95214,
    "lon": -60.84153,
    "cerrado": true,
    "ppm2": 81,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "inmobiliaria-parque",
    "nombre": "Inmobiliaria Parque",
    "ciudad": "Funes",
    "lat": -32.92233,
    "lon": -60.81963,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "islas-malvinas",
    "nombre": "Islas Malvinas",
    "ciudad": "Funes",
    "lat": -32.89157,
    "lon": -60.79202,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "kentucky",
    "ppm2Curado": 200,
    "nombre": "Kentucky",
    "ciudad": "Funes",
    "lat": -32.94339,
    "lon": -60.82799,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "km-318",
    "nombre": "KM 318",
    "ciudad": "Funes",
    "lat": -32.92685,
    "lon": -60.79934,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "km-323",
    "nombre": "KM 323",
    "ciudad": "Funes",
    "lat": -32.91381,
    "lon": -60.85138,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-cardera",
    "nombre": "La Cardera",
    "ciudad": "Funes",
    "lat": -32.9309,
    "lon": -60.82724,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-finca-country-club",
    "nombre": "La Finca Country Club",
    "ciudad": "Funes",
    "lat": -32.93089,
    "lon": -60.77069,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-finca-ii",
    "nombre": "La Finca II",
    "ciudad": "Funes",
    "lat": -32.90776,
    "lon": -60.81945,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-florida",
    "nombre": "La Florida",
    "ciudad": "Funes",
    "lat": -32.91506,
    "lon": -60.80607,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-guillermina",
    "nombre": "La Guillermina",
    "ciudad": "Funes",
    "lat": -32.89599,
    "lon": -60.85522,
    "cerrado": false,
    "ppm2": 82,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-rural",
    "nombre": "La Rural",
    "ciudad": "Funes",
    "lat": -32.91534,
    "lon": -60.84105,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-siesta",
    "nombre": "La Siesta",
    "ciudad": "Funes",
    "lat": -32.91696,
    "lon": -60.8345,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-calandrias",
    "nombre": "Las Calandrias",
    "ciudad": "Funes",
    "lat": -32.92187,
    "lon": -60.84949,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-glicinas",
    "nombre": "Las Glicinas",
    "ciudad": "Funes",
    "lat": -32.91365,
    "lon": -60.80185,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-glicinas-2",
    "nombre": "Las Glicinas 2",
    "ciudad": "Funes",
    "lat": -32.91361,
    "lon": -60.8021,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-glicinas-3",
    "nombre": "Las Glicinas 3",
    "ciudad": "Funes",
    "lat": -32.91293,
    "lon": -60.80192,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-quintas",
    "nombre": "Las Quintas",
    "ciudad": "Funes",
    "lat": -32.9223,
    "lon": -60.85771,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "latucca-y-mondini",
    "nombre": "Latucca y Mondini",
    "ciudad": "Funes",
    "lat": -32.9143,
    "lon": -60.83046,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "lomas-de-funes",
    "nombre": "Lomas de Funes",
    "ciudad": "Funes",
    "lat": -32.90529,
    "lon": -60.81476,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-2-chinos",
    "nombre": "Los 2 chinos",
    "ciudad": "Funes",
    "lat": -32.92557,
    "lon": -60.80227,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-aljibes",
    "nombre": "Los Aljibes",
    "ciudad": "Funes",
    "lat": -32.93061,
    "lon": -60.82159,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-chalecitos",
    "nombre": "Los Chalecitos",
    "ciudad": "Funes",
    "lat": -32.91769,
    "lon": -60.81724,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-girasoles",
    "nombre": "Los Girasoles",
    "ciudad": "Funes",
    "lat": -32.93102,
    "lon": -60.8341,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-morros",
    "nombre": "Los Morros",
    "ciudad": "Funes",
    "lat": -32.93356,
    "lon": -60.83066,
    "cerrado": false,
    "ppm2": 128,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-nogales",
    "nombre": "Los Nogales",
    "ciudad": "Funes",
    "lat": -32.91789,
    "lon": -60.82318,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-solares",
    "nombre": "Los Solares",
    "ciudad": "Funes",
    "lat": -32.92549,
    "lon": -60.78985,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-troncos",
    "ppm2Curado": 200,
    "nombre": "Los Troncos",
    "ciudad": "Funes",
    "lat": -32.9257,
    "lon": -60.8185,
    "cerrado": false,
    "ppm2": 211,
    "muestras": 2,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "maria-auxiliadora",
    "nombre": "María Auxiliadora",
    "ciudad": "Funes",
    "lat": -32.91323,
    "lon": -60.80023,
    "cerrado": false,
    "ppm2": 180,
    "muestras": 4,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "miraflores",
    "ppm2Curado": 220,
    "nombre": "Miraflores",
    "ciudad": "Funes",
    "lat": -32.92681,
    "lon": -60.84021,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "mojon-de-funes",
    "nombre": "Mojón de Funes",
    "ciudad": "Funes",
    "lat": -32.91546,
    "lon": -60.8323,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "ocho-sauces",
    "nombre": "Ocho Sauces",
    "ciudad": "Funes",
    "lat": -32.92503,
    "lon": -60.83567,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "pao-pey",
    "nombre": "Pao Pey",
    "ciudad": "Funes",
    "lat": -32.91315,
    "lon": -60.84019,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "paseo-del-norte",
    "nombre": "Paseo del Norte",
    "ciudad": "Funes",
    "lat": -32.89676,
    "lon": -60.81199,
    "cerrado": false,
    "ppm2": 96,
    "muestras": 3,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "proa-200",
    "nombre": "Proa 200",
    "ciudad": "Funes",
    "lat": -32.92228,
    "lon": -60.84103,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "profesional-country-club",
    "nombre": "Profesional Country Club",
    "ciudad": "Funes",
    "lat": -32.91695,
    "lon": -60.85664,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "propio-hogar",
    "nombre": "Propio Hogar",
    "ciudad": "Funes",
    "lat": -32.91198,
    "lon": -60.84673,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "pueblo-funes",
    "nombre": "Pueblo Funes",
    "ciudad": "Funes",
    "lat": -32.90952,
    "lon": -60.81665,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "puente-golf",
    "nombre": "Puente Golf",
    "ciudad": "Funes",
    "lat": -32.92541,
    "lon": -60.76469,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "puerta-del-sol",
    "nombre": "Puerta del Sol",
    "ciudad": "Funes",
    "lat": -32.92306,
    "lon": -60.78065,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "quinta-natacha",
    "nombre": "Quinta Natacha",
    "ciudad": "Funes",
    "lat": -32.89272,
    "lon": -60.82654,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "residencial-funes",
    "nombre": "Residencial Funes",
    "ciudad": "Funes",
    "lat": -32.91814,
    "lon": -60.84193,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "rincon-de-funes",
    "nombre": "Rincón de Funes",
    "ciudad": "Funes",
    "lat": -32.91991,
    "lon": -60.80105,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "rincon-de-la-arboleda",
    "nombre": "Rincón de la Arboleda",
    "ciudad": "Funes",
    "lat": -32.91468,
    "lon": -60.84849,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "rio-de-pajaros",
    "nombre": "Río de Pájaros",
    "ciudad": "Funes",
    "lat": -32.91144,
    "lon": -60.80134,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "rudof",
    "nombre": "Rudof",
    "ciudad": "Funes",
    "lat": -32.90945,
    "lon": -60.81151,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-alberto-2",
    "nombre": "San Alberto 2",
    "ciudad": "Funes",
    "lat": -32.92149,
    "lon": -60.86385,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-jose",
    "nombre": "San José",
    "ciudad": "Funes",
    "lat": -32.91989,
    "lon": -60.81132,
    "cerrado": false,
    "ppm2": 107,
    "muestras": 2,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-juan",
    "nombre": "San Juan",
    "ciudad": "Funes",
    "lat": -32.93084,
    "lon": -60.80079,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2083,
    "muestrasDepto": 5
  },
  {
    "slug": "san-marino",
    "ppm2Curado": 250,
    "nombre": "San Marino",
    "ciudad": "Funes",
    "lat": -32.92743,
    "lon": -60.82374,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-sebastian",
    "ppm2Curado": 238,
    "nombre": "San Sebastián",
    "ciudad": "Funes",
    "lat": -32.93342,
    "lon": -60.8082,
    "cerrado": true,
    "ppm2": 253,
    "muestras": 3,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-telmo",
    "nombre": "San Telmo",
    "ciudad": "Funes",
    "lat": -32.91352,
    "lon": -60.81367,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-isabel-3",
    "nombre": "Santa Isabel 3",
    "ciudad": "Funes",
    "lat": -32.91314,
    "lon": -60.8595,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-isabel-4",
    "nombre": "Santa Isabel 4",
    "ciudad": "Funes",
    "lat": -32.91034,
    "lon": -60.86031,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "scaglione",
    "nombre": "Scaglione",
    "ciudad": "Funes",
    "lat": -32.92263,
    "lon": -60.81751,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "sol-de-funes",
    "nombre": "Sol de Funes",
    "ciudad": "Funes",
    "lat": -32.93794,
    "lon": -60.8358,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "terraz-funes",
    "nombre": "Terraz Funes",
    "ciudad": "Funes",
    "lat": -32.91332,
    "lon": -60.81317,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tomas-de-la-torre",
    "nombre": "Tomás de la Torre",
    "ciudad": "Funes",
    "lat": -32.92221,
    "lon": -60.78834,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "top-funes",
    "nombre": "Top Funes",
    "ciudad": "Funes",
    "lat": -32.91418,
    "lon": -60.83539,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "travaccio",
    "nombre": "Travaccio",
    "ciudad": "Funes",
    "lat": -32.92158,
    "lon": -60.79371,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "turcatto",
    "nombre": "Turcatto",
    "ciudad": "Funes",
    "lat": -32.91388,
    "lon": -60.85267,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vazquez-rey",
    "nombre": "Vazquez Rey",
    "ciudad": "Funes",
    "lat": -32.91158,
    "lon": -60.81008,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "velez-sarsfield",
    "nombre": "Vélez Sarsfield",
    "ciudad": "Funes",
    "lat": -32.90946,
    "lon": -60.81458,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vida",
    "nombre": "Vida",
    "ciudad": "Funes",
    "lat": -32.93143,
    "lon": -60.79352,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vida-club-de-campo",
    "ppm2Curado": 130,
    "nombre": "Vida Club de Campo",
    "ciudad": "Funes",
    "lat": -32.93635,
    "lon": -60.78773,
    "cerrado": true,
    "ppm2": 146,
    "muestras": 2,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vida-crystal-lagoon",
    "ppm2Curado": 123,
    "nombre": "Vida Crystal Lagoon",
    "ciudad": "Funes",
    "lat": -32.9055,
    "lon": -60.84776,
    "cerrado": true,
    "ppm2": 141,
    "muestras": 4,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vida-green",
    "ppm2Curado": 120,
    "nombre": "Vida Green",
    "ciudad": "Funes",
    "lat": -32.89658,
    "lon": -60.8019,
    "cerrado": true,
    "ppm2": 110,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vida-jardin",
    "nombre": "Vida Jardín",
    "ciudad": "Funes",
    "lat": -32.93174,
    "lon": -60.85246,
    "cerrado": true,
    "ppm2": 168,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-del-sol",
    "nombre": "Villa del Sol",
    "ciudad": "Funes",
    "lat": -32.90488,
    "lon": -60.80902,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-elvira",
    "nombre": "Villa Elvira",
    "ciudad": "Funes",
    "lat": -32.91426,
    "lon": -60.79626,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-ercolina",
    "nombre": "Villa Ercolina",
    "ciudad": "Funes",
    "lat": -32.90932,
    "lon": -60.80541,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-golf",
    "nombre": "Villa Golf",
    "ciudad": "Funes",
    "lat": -32.92626,
    "lon": -60.77159,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "acequias-del-aire",
    "ppm2Curado": 75,
    "nombre": "Acequias del Aire",
    "ciudad": "Roldán",
    "lat": -32.89737,
    "lon": -60.87255,
    "cerrado": false,
    "ppm2": 106,
    "muestras": 3,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "aires-de-campo",
    "nombre": "Aires de Campo",
    "ciudad": "Roldán",
    "lat": -32.91275,
    "lon": -60.87433,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "alto-residencial",
    "nombre": "Alto Residencial",
    "ciudad": "Roldán",
    "lat": -32.88311,
    "lon": -60.89203,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "alto-verde",
    "nombre": "Alto Verde",
    "ciudad": "Roldán",
    "lat": -32.91492,
    "lon": -60.87218,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "altos-de-pellegrini",
    "nombre": "Altos de Pellegrini",
    "ciudad": "Roldán",
    "lat": -32.89699,
    "lon": -60.91751,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "altos-del-este",
    "nombre": "Altos del Este",
    "ciudad": "Roldán",
    "lat": -32.89993,
    "lon": -60.89813,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "america",
    "nombre": "América",
    "ciudad": "Roldán",
    "lat": -32.89596,
    "lon": -60.91082,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "arrabal",
    "nombre": "Arrabal",
    "ciudad": "Roldán",
    "lat": -32.89691,
    "lon": -60.90258,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "aurea",
    "nombre": "Áurea",
    "ciudad": "Roldán",
    "lat": -32.88705,
    "lon": -60.89298,
    "cerrado": false,
    "ppm2": 70,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "beaudrix",
    "nombre": "Beaudrix",
    "ciudad": "Roldán",
    "lat": -32.8911,
    "lon": -60.9046,
    "cerrado": false,
    "ppm2": 78,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "belisario-roldan",
    "nombre": "Belisario Roldán",
    "ciudad": "Roldán",
    "lat": -32.89625,
    "lon": -60.89652,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "bosque-azul",
    "ppm2Curado": 65,
    "nombre": "Bosque Azul",
    "ciudad": "Roldán",
    "lat": -32.91576,
    "lon": -60.88829,
    "cerrado": true,
    "ppm2": 77,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "brofft",
    "nombre": "Brofft",
    "ciudad": "Roldán",
    "lat": -32.89501,
    "lon": -60.91631,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "capra",
    "nombre": "Capra",
    "ciudad": "Roldán",
    "lat": -32.91263,
    "lon": -60.87987,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "chacra-los-raigales",
    "nombre": "Chacra Los Raigales",
    "ciudad": "Roldán",
    "lat": -32.94684,
    "lon": -60.89615,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cotitos-r",
    "nombre": "Cotitos R",
    "ciudad": "Roldán",
    "lat": -32.90744,
    "lon": -60.86905,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cotos-de-la-alameda",
    "ppm2Curado": 75,
    "nombre": "Cotos de la Alameda",
    "ciudad": "Roldán",
    "lat": -32.90799,
    "lon": -60.877,
    "cerrado": true,
    "ppm2": 72,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cotos-de-la-alameda-ii",
    "ppm2Curado": 75,
    "nombre": "Cotos de la Alameda II",
    "ciudad": "Roldán",
    "lat": -32.90484,
    "lon": -60.8845,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cotos-unanue",
    "nombre": "Cotos Unanue",
    "ciudad": "Roldán",
    "lat": -32.90701,
    "lon": -60.87106,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "delle-vedove",
    "nombre": "Delle Vedove",
    "ciudad": "Roldán",
    "lat": -32.945,
    "lon": -60.91058,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "distrito-roldan",
    "ppm2Curado": 88,
    "nombre": "Distrito Roldán",
    "ciudad": "Roldán",
    "lat": -32.91138,
    "lon": -60.88838,
    "cerrado": false,
    "ppm2": 180,
    "muestras": 4,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "don-quijote",
    "ppm2Curado": 65,
    "nombre": "Don Quijote",
    "ciudad": "Roldán",
    "lat": -32.91094,
    "lon": -60.89279,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "edelweiss",
    "nombre": "Edelweiss",
    "ciudad": "Roldán",
    "lat": -32.90827,
    "lon": -60.86744,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-alba",
    "nombre": "El Alba",
    "ciudad": "Roldán",
    "lat": -32.87057,
    "lon": -60.88385,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-charquito",
    "nombre": "El Charquito",
    "ciudad": "Roldán",
    "lat": -32.90273,
    "lon": -60.9127,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-cielo",
    "nombre": "El Cielo",
    "ciudad": "Roldán",
    "lat": -32.91207,
    "lon": -60.88111,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-cruce",
    "nombre": "El Cruce",
    "ciudad": "Roldán",
    "lat": -32.90858,
    "lon": -60.89657,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-descanso",
    "nombre": "El Descanso",
    "ciudad": "Roldán",
    "lat": -32.92243,
    "lon": -60.90174,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-eden",
    "ppm2Curado": 65,
    "nombre": "El Edén",
    "ciudad": "Roldán",
    "lat": -32.91355,
    "lon": -60.88855,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-molino",
    "ppm2Curado": 70,
    "nombre": "El Molino",
    "ciudad": "Roldán",
    "lat": -32.92674,
    "lon": -60.87393,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-sol-naciente",
    "nombre": "El Sol Naciente",
    "ciudad": "Roldán",
    "lat": -32.90455,
    "lon": -60.89059,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-summun",
    "nombre": "El Summun",
    "ciudad": "Roldán",
    "lat": -32.90979,
    "lon": -60.86614,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-troncal",
    "nombre": "El Troncal",
    "ciudad": "Roldán",
    "lat": -32.90509,
    "lon": -60.89233,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "estacion-roldan",
    "ppm2Curado": 150,
    "nombre": "Estación Roldán",
    "ciudad": "Roldán",
    "lat": -32.90167,
    "lon": -60.87941,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "estancia-la-catalina",
    "nombre": "Estancia La Catalina",
    "ciudad": "Roldán",
    "lat": -32.93234,
    "lon": -60.9155,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fontanet",
    "nombre": "Fontanet",
    "ciudad": "Roldán",
    "lat": -32.92373,
    "lon": -60.90204,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "funes-town",
    "ppm2Curado": 90,
    "nombre": "Funes Town",
    "ciudad": "Roldán",
    "lat": -32.90064,
    "lon": -60.86024,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-estancia-i",
    "nombre": "La Estancia I",
    "ciudad": "Roldán",
    "lat": -32.90563,
    "lon": -60.86722,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-estancia-ii",
    "nombre": "La Estancia II",
    "ciudad": "Roldán",
    "lat": -32.89744,
    "lon": -60.86695,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-ilusion-polo-lakeside",
    "nombre": "La Ilusión Polo & Lakeside",
    "ciudad": "Roldán",
    "lat": -32.9291,
    "lon": -60.929,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-ilusion-ranches",
    "nombre": "La Ilusión Ranches",
    "ciudad": "Roldán",
    "lat": -32.92527,
    "lon": -60.92556,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-acequias",
    "ppm2Curado": 75,
    "nombre": "Las Acequias",
    "ciudad": "Roldán",
    "lat": -32.89673,
    "lon": -60.8836,
    "cerrado": false,
    "ppm2": 110,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-estacas-i",
    "nombre": "Las Estacas I",
    "ciudad": "Roldán",
    "lat": -32.90585,
    "lon": -60.9137,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-estacas-ii",
    "nombre": "Las Estacas II",
    "ciudad": "Roldán",
    "lat": -32.90746,
    "lon": -60.89053,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-palmeras",
    "nombre": "Las Palmeras",
    "ciudad": "Roldán",
    "lat": -32.88919,
    "lon": -60.88685,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-tardes",
    "nombre": "Las Tardes",
    "ciudad": "Roldán",
    "lat": -32.88678,
    "lon": -60.88107,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "lenaue",
    "nombre": "Lenaue",
    "ciudad": "Roldán",
    "lat": -32.90499,
    "lon": -60.86438,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-aromos",
    "nombre": "Los Aromos",
    "ciudad": "Roldán",
    "lat": -32.91516,
    "lon": -60.88042,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-cedros",
    "nombre": "Los Cedros",
    "ciudad": "Roldán",
    "lat": -32.89172,
    "lon": -60.88842,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-cocos",
    "nombre": "Los Cocos",
    "ciudad": "Roldán",
    "lat": -32.90682,
    "lon": -60.91678,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-indios",
    "nombre": "Los Indios",
    "ciudad": "Roldán",
    "lat": -32.90298,
    "lon": -60.86899,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-olmos",
    "nombre": "Los Olmos",
    "ciudad": "Roldán",
    "lat": -32.90462,
    "lon": -60.89635,
    "cerrado": false,
    "ppm2": 87,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-rosales",
    "nombre": "Los Rosales",
    "ciudad": "Roldán",
    "lat": -32.91298,
    "lon": -60.87707,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "maiz",
    "nombre": "Maíz",
    "ciudad": "Roldán",
    "lat": -32.91153,
    "lon": -60.88549,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "makey",
    "nombre": "Makey",
    "ciudad": "Roldán",
    "lat": -32.86056,
    "lon": -60.88663,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "marcos-ateca",
    "nombre": "Marcos Ateca",
    "ciudad": "Roldán",
    "lat": -32.90667,
    "lon": -60.90676,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "maria-esther",
    "nombre": "María Esther",
    "ciudad": "Roldán",
    "lat": -32.90534,
    "lon": -60.88675,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "mazzoni-de-bernaschini",
    "nombre": "Mazzoni de Bernaschini",
    "ciudad": "Roldán",
    "lat": -32.91244,
    "lon": -60.87862,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "mi-sosiego",
    "nombre": "Mi Sosiego",
    "ciudad": "Roldán",
    "lat": -32.9109,
    "lon": -60.86908,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "muradore",
    "nombre": "Muradore",
    "ciudad": "Roldán",
    "lat": -32.89998,
    "lon": -60.91813,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "nadine",
    "nombre": "Nadine",
    "ciudad": "Roldán",
    "lat": -32.90792,
    "lon": -60.91546,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-esmeralda",
    "nombre": "Parque Esmeralda",
    "ciudad": "Roldán",
    "lat": -32.90789,
    "lon": -60.88444,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "posta-16",
    "nombre": "Posta 16",
    "ciudad": "Roldán",
    "lat": -32.89089,
    "lon": -60.89692,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "prados-del-sol",
    "nombre": "Prados del Sol",
    "ciudad": "Roldán",
    "lat": -32.92176,
    "lon": -60.87316,
    "cerrado": true,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "prosperity-lands",
    "nombre": "Prosperity Lands",
    "ciudad": "Roldán",
    "lat": -32.89811,
    "lon": -60.87801,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "pucara-los-buhos",
    "nombre": "Pucará Los Buhos",
    "ciudad": "Roldán",
    "lat": -32.92126,
    "lon": -60.9067,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "puerto-roldan",
    "nombre": "Puerto Roldán",
    "ciudad": "Roldán",
    "lat": -32.93353,
    "lon": -60.88506,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "punta-chacra",
    "ppm2Curado": 50,
    "nombre": "Punta Chacra",
    "ciudad": "Roldán",
    "lat": -32.91503,
    "lon": -60.9367,
    "cerrado": false,
    "ppm2": 43,
    "muestras": 1,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "punta-chacra-weekend-1",
    "nombre": "Punta Chacra Weekend 1",
    "ciudad": "Roldán",
    "lat": -32.91039,
    "lon": -60.93293,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "punta-chacra-weekend-2",
    "nombre": "Punta Chacra Weekend 2",
    "ciudad": "Roldán",
    "lat": -32.90969,
    "lon": -60.93765,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "quintas-de-funes",
    "nombre": "Quintas de Funes",
    "ciudad": "Roldán",
    "lat": -32.92789,
    "lon": -60.86519,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-alberto",
    "nombre": "San Alberto",
    "ciudad": "Roldán",
    "lat": -32.91756,
    "lon": -60.86349,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-andres",
    "ppm2Curado": 75,
    "nombre": "San Andrés",
    "ciudad": "Roldán",
    "lat": -32.89984,
    "lon": -60.89591,
    "cerrado": false,
    "ppm2": 91,
    "muestras": 3,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-eduardo-i",
    "nombre": "San Eduardo I",
    "ciudad": "Roldán",
    "lat": -32.90763,
    "lon": -60.88785,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-javier",
    "nombre": "San Javier",
    "ciudad": "Roldán",
    "lat": -32.90497,
    "lon": -60.9164,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-isabel-1",
    "nombre": "Santa Isabel 1",
    "ciudad": "Roldán",
    "lat": -32.91289,
    "lon": -60.86407,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-isabel-2",
    "nombre": "Santa Isabel 2",
    "ciudad": "Roldán",
    "lat": -32.91162,
    "lon": -60.86343,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-isabel-5",
    "nombre": "Santa Isabel 5",
    "ciudad": "Roldán",
    "lat": -32.90995,
    "lon": -60.86296,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-isabel-j-a",
    "nombre": "Santa Isabel J.A.",
    "ciudad": "Roldán",
    "lat": -32.91658,
    "lon": -60.86707,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-teresa",
    "nombre": "Santa Teresa",
    "ciudad": "Roldán",
    "lat": -32.89935,
    "lon": -60.89026,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santo-domingo",
    "nombre": "Santo Domingo",
    "ciudad": "Roldán",
    "lat": -32.9025,
    "lon": -60.91923,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tierra-de-suenos-1",
    "ppm2Curado": 65,
    "nombre": "Tierra de Sueños 1",
    "ciudad": "Roldán",
    "lat": -32.89342,
    "lon": -60.89756,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tierra-de-suenos-2",
    "ppm2Curado": 75,
    "nombre": "Tierra de Sueños 2",
    "ciudad": "Roldán",
    "lat": -32.93116,
    "lon": -60.89312,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tierra-de-suenos-3",
    "ppm2Curado": 60,
    "nombre": "Tierra de Sueños 3",
    "ciudad": "Roldán",
    "lat": -32.94758,
    "lon": -60.88475,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "travattore-giandomenico",
    "nombre": "Travattore Giandoménico",
    "ciudad": "Roldán",
    "lat": -32.90802,
    "lon": -60.88592,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tu-lugar",
    "nombre": "Tu Lugar",
    "ciudad": "Roldán",
    "lat": -32.92078,
    "lon": -60.90119,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-alda",
    "nombre": "Villa Alda",
    "ciudad": "Roldán",
    "lat": -32.911,
    "lon": -60.89835,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-alicia",
    "nombre": "Villa Alicia",
    "ciudad": "Roldán",
    "lat": -32.91895,
    "lon": -60.87259,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-celina",
    "nombre": "Villa Celina",
    "ciudad": "Roldán",
    "lat": -32.91413,
    "lon": -60.89855,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-eduardito",
    "nombre": "Villa Eduardito",
    "ciudad": "Roldán",
    "lat": -32.86043,
    "lon": -60.88163,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-flores",
    "nombre": "Villa Flores",
    "ciudad": "Roldán",
    "lat": -32.9092,
    "lon": -60.90662,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-lourdes-1",
    "nombre": "Villa Lourdes 1",
    "ciudad": "Roldán",
    "lat": -32.91319,
    "lon": -60.86944,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-lourdes-2",
    "nombre": "Villa Lourdes 2",
    "ciudad": "Roldán",
    "lat": -32.9166,
    "lon": -60.8706,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "wirth",
    "nombre": "Wirth",
    "ciudad": "Roldán",
    "lat": -32.90905,
    "lon": -60.86765,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "rosario",
    "nombre": "Rosario",
    "ciudad": "Rosario",
    "lat": -32.9468,
    "lon": -60.6393,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2182,
    "muestrasDepto": 61
  },
  {
    "slug": "centro-rosario",
    "nombre": "Centro",
    "ciudad": "Rosario",
    "lat": -32.9468,
    "lon": -60.6393,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2218,
    "muestrasDepto": 21
  },
  {
    "slug": "pichincha",
    "nombre": "Pichincha",
    "ciudad": "Rosario",
    "lat": -32.935,
    "lon": -60.648,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2562,
    "muestrasDepto": 5
  },
  {
    "slug": "macrocentro",
    "nombre": "Macrocentro",
    "ciudad": "Rosario",
    "lat": -32.952,
    "lon": -60.652,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2790,
    "muestrasDepto": 1
  },
  {
    "slug": "microcentro",
    "nombre": "Microcentro",
    "ciudad": "Rosario",
    "lat": -32.944,
    "lon": -60.64,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1364,
    "muestrasDepto": 1
  },
  {
    "slug": "refineria",
    "nombre": "Refinería",
    "ciudad": "Rosario",
    "lat": -32.92,
    "lon": -60.66,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "arroyito",
    "nombre": "Arroyito",
    "ciudad": "Rosario",
    "lat": -32.91,
    "lon": -60.67,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "14-de-octubre",
    "nombre": "14 de Octubre",
    "ciudad": "Rosario",
    "lat": -32.997,
    "lon": -60.66342,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "17-de-agosto",
    "nombre": "17 de Agosto",
    "ciudad": "Rosario",
    "lat": -33.01189,
    "lon": -60.66006,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "7-de-septiembre",
    "nombre": "7 de Septiembre",
    "ciudad": "Rosario",
    "lat": -32.9117,
    "lon": -60.73189,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "abasto",
    "nombre": "Abasto",
    "ciudad": "Rosario",
    "lat": -32.96164,
    "lon": -60.64705,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "acindar",
    "nombre": "Acindar",
    "ciudad": "Rosario",
    "lat": -32.98408,
    "lon": -60.67983,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "alberdi",
    "nombre": "Alberdi",
    "ciudad": "Rosario",
    "lat": -32.89509,
    "lon": -60.69318,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "albert-schweitzer",
    "nombre": "Albert Schweitzer",
    "ciudad": "Rosario",
    "lat": -32.91236,
    "lon": -60.71496,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "alberto-olmedo",
    "nombre": "Alberto Olmedo",
    "ciudad": "Rosario",
    "lat": -32.93821,
    "lon": -60.65968,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "aldea-del-lago",
    "nombre": "Aldea del Lago",
    "ciudad": "Rosario",
    "lat": -32.91164,
    "lon": -60.75304,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "altos-de-mendoza",
    "nombre": "Altos de Mendoza",
    "ciudad": "Rosario",
    "lat": -32.94515,
    "lon": -60.72792,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "alvear",
    "nombre": "Alvear",
    "ciudad": "Rosario",
    "lat": -32.97746,
    "lon": -60.67851,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "amiga",
    "nombre": "Amiga",
    "ciudad": "Rosario",
    "lat": -32.92107,
    "lon": -60.73056,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "antartida-argentina",
    "nombre": "Antártida Argentina",
    "ciudad": "Rosario",
    "lat": -32.9342,
    "lon": -60.73137,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "arboria",
    "nombre": "Arboria",
    "ciudad": "Rosario",
    "lat": -32.9473,
    "lon": -60.7686,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "azcuenaga",
    "nombre": "Azcuénaga",
    "ciudad": "Rosario",
    "lat": -32.9426,
    "lon": -60.69836,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "barrio-ingles",
    "nombre": "Barrio Inglés",
    "ciudad": "Rosario",
    "lat": -32.92961,
    "lon": -60.67304,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "barrio-moreno",
    "nombre": "Barrio Moreno",
    "ciudad": "Rosario",
    "lat": -32.98058,
    "lon": -60.66015,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "belgrano",
    "nombre": "Belgrano",
    "ciudad": "Rosario",
    "lat": -32.94097,
    "lon": -60.71336,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 3987,
    "muestrasDepto": 1
  },
  {
    "slug": "bella-vista",
    "nombre": "Bella Vista",
    "ciudad": "Rosario",
    "lat": -32.96675,
    "lon": -60.68081,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "bernardo-de-irigoyen",
    "nombre": "Bernardo de Irigoyen",
    "ciudad": "Rosario",
    "lat": -33.0135,
    "lon": -60.64973,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "celedonio-escalada",
    "nombre": "Celedonio Escalada",
    "ciudad": "Rosario",
    "lat": -32.87493,
    "lon": -60.72998,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cinco-esquinas",
    "nombre": "Cinco Esquinas",
    "ciudad": "Rosario",
    "lat": -32.95435,
    "lon": -60.68203,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "ciudad-ribera",
    "nombre": "Ciudad Ribera",
    "ciudad": "Rosario",
    "lat": -32.92343,
    "lon": -60.66379,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "club-duendes",
    "nombre": "Club Duendes",
    "ciudad": "Rosario",
    "lat": -33.00564,
    "lon": -60.68491,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "colombres",
    "nombre": "Colombres",
    "ciudad": "Rosario",
    "lat": -32.93362,
    "lon": -60.74183,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condo-del-bosque",
    "nombre": "Condo del Bosque",
    "ciudad": "Rosario",
    "lat": -32.89687,
    "lon": -60.73651,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominios-del-alto",
    "nombre": "Condominios del Alto",
    "ciudad": "Rosario",
    "lat": -32.92793,
    "lon": -60.66482,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condominios-palos-verdes",
    "nombre": "Condominios Palos Verdes",
    "ciudad": "Rosario",
    "lat": -32.89978,
    "lon": -60.7462,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "condos-tierra-nueva",
    "nombre": "Condos Tierra Nueva",
    "ciudad": "Rosario",
    "lat": -32.93124,
    "lon": -60.76362,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cordon-ayacucho",
    "nombre": "Cordón Ayacucho",
    "ciudad": "Rosario",
    "lat": -32.98852,
    "lon": -60.63513,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "country-carlos-pellegrini",
    "nombre": "Country Carlos Pellegrini",
    "ciudad": "Rosario",
    "lat": -32.9327,
    "lon": -60.75509,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "country-golf-rosario",
    "nombre": "Country Golf Rosario",
    "ciudad": "Rosario",
    "lat": -32.92091,
    "lon": -60.77199,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "country-tenis-aldea",
    "nombre": "Country Tenis Aldea",
    "ciudad": "Rosario",
    "lat": -32.91178,
    "lon": -60.75806,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "cristaleria",
    "nombre": "Cristalería",
    "ciudad": "Rosario",
    "lat": -32.88135,
    "lon": -60.73156,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "domingo-faustino-sarmiento",
    "nombre": "Domingo Faustino Sarmiento",
    "ciudad": "Rosario",
    "lat": -32.90643,
    "lon": -60.68773,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "domingo-matheu",
    "nombre": "Domingo Matheu",
    "ciudad": "Rosario",
    "lat": -32.98186,
    "lon": -60.65377,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "echesortu",
    "nombre": "Echesortu",
    "ciudad": "Rosario",
    "lat": -32.9436,
    "lon": -60.68237,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1978,
    "muestrasDepto": 3
  },
  {
    "slug": "el-grafico",
    "nombre": "El Gráfico",
    "ciudad": "Rosario",
    "lat": -32.9362,
    "lon": -60.74541,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "el-mangrullo",
    "nombre": "El Mangrullo",
    "ciudad": "Rosario",
    "lat": -32.99794,
    "lon": -60.61588,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "empalme-graneros",
    "nombre": "Empalme Graneros",
    "ciudad": "Rosario",
    "lat": -32.92113,
    "lon": -60.70693,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "espana-y-hospitales",
    "nombre": "España y Hospitales",
    "ciudad": "Rosario",
    "lat": -32.97138,
    "lon": -60.65234,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "estacion-el-gaucho",
    "nombre": "Estación El Gaucho",
    "ciudad": "Rosario",
    "lat": -33.00524,
    "lon": -60.68727,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "esteban-echeverria",
    "nombre": "Esteban Echeverría",
    "ciudad": "Rosario",
    "lat": -32.99499,
    "lon": -60.62423,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fisherton",
    "nombre": "Fisherton",
    "ciudad": "Rosario",
    "lat": -32.91857,
    "lon": -60.73818,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2105,
    "muestrasDepto": 9
  },
  {
    "slug": "fisherton-del-este",
    "nombre": "Fisherton del Este",
    "ciudad": "Rosario",
    "lat": -32.91227,
    "lon": -60.7193,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fisherton-industrial",
    "nombre": "Fisherton Industrial",
    "ciudad": "Rosario",
    "lat": -32.92365,
    "lon": -60.71847,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fisherton-r",
    "nombre": "Fisherton R.",
    "ciudad": "Rosario",
    "lat": -32.92627,
    "lon": -60.75734,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1728,
    "muestrasDepto": 1
  },
  {
    "slug": "floresta",
    "nombre": "Floresta",
    "ciudad": "Rosario",
    "lat": -32.94294,
    "lon": -60.76072,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fonavi-a-donado-y-mendoza",
    "nombre": "Fonavi A Donado y Mendoza",
    "ciudad": "Rosario",
    "lat": -32.94377,
    "lon": -60.72453,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fonavi-b-donado-y-mendoza",
    "nombre": "Fonavi B Donado y Mendoza",
    "ciudad": "Rosario",
    "lat": -32.93804,
    "lon": -60.72578,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "fonavi-casiano-casas",
    "nombre": "Fonavi Casiano Casas",
    "ciudad": "Rosario",
    "lat": -32.89805,
    "lon": -60.71305,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "forum-puerto-norte",
    "nombre": "Forum Puerto Norte",
    "ciudad": "Rosario",
    "lat": -32.92225,
    "lon": -60.66514,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "general-las-heras",
    "nombre": "General Las Heras",
    "ciudad": "Rosario",
    "lat": -32.98746,
    "lon": -60.63723,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "general-san-martin",
    "nombre": "General San Martín",
    "ciudad": "Rosario",
    "lat": -32.97648,
    "lon": -60.63726,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "godoy",
    "nombre": "Godoy",
    "ciudad": "Rosario",
    "lat": -32.96509,
    "lon": -60.7212,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "grandoli",
    "nombre": "Grandoli",
    "ciudad": "Rosario",
    "lat": -32.99276,
    "lon": -60.62778,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "greenes-de-fisherton",
    "nombre": "Greenes de Fisherton",
    "ciudad": "Rosario",
    "lat": -32.91635,
    "lon": -60.77454,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "hostal-del-sol",
    "nombre": "Hostal del Sol",
    "ciudad": "Rosario",
    "lat": -32.90479,
    "lon": -60.75163,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "hostal-del-sol-oeste",
    "nombre": "Hostal del Sol Oeste",
    "ciudad": "Rosario",
    "lat": -32.90502,
    "lon": -60.76391,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "hoyo-12",
    "nombre": "Hoyo 12",
    "ciudad": "Rosario",
    "lat": -32.92059,
    "lon": -60.75455,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "hume",
    "nombre": "Hume",
    "ciudad": "Rosario",
    "lat": -33.00198,
    "lon": -60.68403,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "islas-malvinas",
    "nombre": "Islas Malvinas",
    "ciudad": "Rosario",
    "lat": -32.92434,
    "lon": -60.67016,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "jorge-cura",
    "nombre": "Jorge Cura",
    "ciudad": "Rosario",
    "lat": -32.96836,
    "lon": -60.66334,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "jose-ignacio-rucci",
    "nombre": "Jose Ignacio Rucci",
    "ciudad": "Rosario",
    "lat": -32.88858,
    "lon": -60.71287,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-bajada",
    "nombre": "La Bajada",
    "ciudad": "Rosario",
    "lat": -32.99145,
    "lon": -60.6413,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-banana",
    "nombre": "La Banana",
    "ciudad": "Rosario",
    "lat": -32.96282,
    "lon": -60.68893,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-ceramica",
    "nombre": "La Cerámica",
    "ciudad": "Rosario",
    "lat": -32.8878,
    "lon": -60.70541,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-esperanza",
    "nombre": "La Esperanza",
    "ciudad": "Rosario",
    "lat": -32.89662,
    "lon": -60.71116,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-floresta",
    "nombre": "La Floresta",
    "ciudad": "Rosario",
    "lat": -32.87231,
    "lon": -60.70801,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-florida",
    "nombre": "La Florida",
    "ciudad": "Rosario",
    "lat": -32.87868,
    "lon": -60.69192,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-granada",
    "nombre": "La Granada",
    "ciudad": "Rosario",
    "lat": -33.01848,
    "lon": -60.64864,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-guardia",
    "nombre": "La Guardia",
    "ciudad": "Rosario",
    "lat": -32.98984,
    "lon": -60.65589,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-roca",
    "nombre": "La Roca",
    "ciudad": "Rosario",
    "lat": -32.97359,
    "lon": -60.69709,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-tablada",
    "nombre": "La Tablada",
    "ciudad": "Rosario",
    "lat": -32.9763,
    "lon": -60.6304,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "la-travesia",
    "nombre": "La Travesía",
    "ciudad": "Rosario",
    "lat": -32.9186,
    "lon": -60.69195,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "larrea",
    "nombre": "Larrea",
    "ciudad": "Rosario",
    "lat": -32.91666,
    "lon": -60.71847,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-delicias",
    "nombre": "Las Delicias",
    "ciudad": "Rosario",
    "lat": -33.00218,
    "lon": -60.67083,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-flores",
    "nombre": "Las Flores",
    "ciudad": "Rosario",
    "lat": -33.01676,
    "lon": -60.65583,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-flores-norte",
    "nombre": "Las Flores Norte",
    "ciudad": "Rosario",
    "lat": -33.0119,
    "lon": -60.65403,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-flores-sur",
    "nombre": "Las Flores Sur",
    "ciudad": "Rosario",
    "lat": -33.0201,
    "lon": -60.65988,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-palmeras",
    "nombre": "Las Palmeras",
    "ciudad": "Rosario",
    "lat": -32.9561,
    "lon": -60.72329,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "las-torcazas",
    "nombre": "Las Torcazas",
    "ciudad": "Rosario",
    "lat": -32.92044,
    "lon": -60.75033,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "latinoamerica",
    "nombre": "Latinoámerica",
    "ciudad": "Rosario",
    "lat": -32.96681,
    "lon": -60.66601,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "lisandro-de-la-torre",
    "nombre": "Lisandro de la Torre",
    "ciudad": "Rosario",
    "lat": -32.91658,
    "lon": -60.67711,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "lomas-de-alberdi",
    "nombre": "Lomas de Alberdi",
    "ciudad": "Rosario",
    "lat": -32.88131,
    "lon": -60.7061,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "lomas-de-fisherton",
    "nombre": "Lomas de Fisherton",
    "ciudad": "Rosario",
    "lat": -32.93836,
    "lon": -60.73598,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-duendes",
    "nombre": "Los Duendes",
    "ciudad": "Rosario",
    "lat": -33.00105,
    "lon": -60.71256,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-humitos",
    "nombre": "Los Humitos",
    "ciudad": "Rosario",
    "lat": -32.97017,
    "lon": -60.72961,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pasos-arroyo",
    "nombre": "Los Pasos Arroyo",
    "ciudad": "Rosario",
    "lat": -32.9454,
    "lon": -60.77354,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pasos-barrios-abierto",
    "nombre": "Los Pasos Barrios Abierto",
    "ciudad": "Rosario",
    "lat": -32.93772,
    "lon": -60.76128,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pasos-country",
    "nombre": "Los Pasos Country",
    "ciudad": "Rosario",
    "lat": -32.93569,
    "lon": -60.75496,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pasos-fisherton",
    "nombre": "Los Pasos Fisherton",
    "ciudad": "Rosario",
    "lat": -32.93859,
    "lon": -60.76313,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pasos-golf",
    "nombre": "Los Pasos Golf",
    "ciudad": "Rosario",
    "lat": -32.93952,
    "lon": -60.76711,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pasos-puente",
    "nombre": "Los Pasos Puente",
    "ciudad": "Rosario",
    "lat": -32.94366,
    "lon": -60.76634,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pinos",
    "nombre": "Los Pinos",
    "ciudad": "Rosario",
    "lat": -32.87952,
    "lon": -60.73275,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-pumitas",
    "nombre": "Los Pumitas",
    "ciudad": "Rosario",
    "lat": -32.91132,
    "lon": -60.70392,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-tilos",
    "nombre": "Los Tilos",
    "ciudad": "Rosario",
    "lat": -32.88595,
    "lon": -60.72948,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "los-unidos",
    "nombre": "Los Unidos",
    "ciudad": "Rosario",
    "lat": -32.93834,
    "lon": -60.7561,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "loteo-avellaneda-oeste",
    "nombre": "Loteo Avellaneda Oeste",
    "ciudad": "Rosario",
    "lat": -32.98021,
    "lon": -60.69249,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "luduena",
    "nombre": "Ludueña",
    "ciudad": "Rosario",
    "lat": -32.93159,
    "lon": -60.69222,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "luis-agote",
    "nombre": "Luis Agote",
    "ciudad": "Rosario",
    "lat": -32.93512,
    "lon": -60.67163,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "magnano",
    "nombre": "Magnano",
    "ciudad": "Rosario",
    "lat": -33.01125,
    "lon": -60.63937,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "martin",
    "nombre": "Martin",
    "ciudad": "Rosario",
    "lat": -32.95391,
    "lon": -60.63042,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1908,
    "muestrasDepto": 6
  },
  {
    "slug": "metra-puerto-norte",
    "nombre": "Metra Puerto Norte",
    "ciudad": "Rosario",
    "lat": -32.92115,
    "lon": -60.6697,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "modena-fisherton",
    "nombre": "Módena Fisherton",
    "ciudad": "Rosario",
    "lat": -32.93323,
    "lon": -60.76247,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "moderno",
    "nombre": "Moderno",
    "ciudad": "Rosario",
    "lat": -32.97761,
    "lon": -60.69993,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "newbery",
    "nombre": "Newbery",
    "ciudad": "Rosario",
    "lat": -32.9066,
    "lon": -60.73421,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "nuestra-senora-de-la-paz",
    "nombre": "Nuestra Señora de la Paz",
    "ciudad": "Rosario",
    "lat": -32.90256,
    "lon": -60.70934,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "nuestra-senora-de-lourdes",
    "nombre": "Nuestra Señora de Lourdes",
    "ciudad": "Rosario",
    "lat": -32.94841,
    "lon": -60.66085,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 2156,
    "muestrasDepto": 8
  },
  {
    "slug": "nueva-fisherton",
    "nombre": "Nueva Fisherton",
    "ciudad": "Rosario",
    "lat": -32.92827,
    "lon": -60.73116,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1902,
    "muestrasDepto": 4
  },
  {
    "slug": "nuevo-alberdi",
    "nombre": "Nuevo Alberdi",
    "ciudad": "Rosario",
    "lat": -32.88867,
    "lon": -60.72492,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "nuevo-alberdi-oeste",
    "nombre": "Nuevo Alberdi Oeste",
    "ciudad": "Rosario",
    "lat": -32.89094,
    "lon": -60.73012,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "palos-verdes",
    "nombre": "Palos Verdes",
    "ciudad": "Rosario",
    "lat": -32.89771,
    "lon": -60.74264,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque",
    "nombre": "Parque",
    "ciudad": "Rosario",
    "lat": -32.95885,
    "lon": -60.66802,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-casado",
    "nombre": "Parque Casado",
    "ciudad": "Rosario",
    "lat": -32.96998,
    "lon": -60.67055,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-casas",
    "nombre": "Parque Casas",
    "ciudad": "Rosario",
    "lat": -32.90551,
    "lon": -60.70074,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-field",
    "nombre": "Parque Field",
    "ciudad": "Rosario",
    "lat": -32.89168,
    "lon": -60.71308,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-habitacional-calasanz",
    "nombre": "Parque Habitacional Calasanz",
    "ciudad": "Rosario",
    "lat": -32.94262,
    "lon": -60.7583,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-habitacional-ibarlucea",
    "nombre": "Parque Habitacional Ibarlucea",
    "ciudad": "Rosario",
    "lat": -32.87526,
    "lon": -60.73622,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-habitacional-ibarlucea-este",
    "nombre": "Parque Habitacional Ibarlucea Este",
    "ciudad": "Rosario",
    "lat": -32.88245,
    "lon": -60.71737,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "parque-regional-sur",
    "nombre": "Parque Regional Sur",
    "ciudad": "Rosario",
    "lat": -33.0054,
    "lon": -60.63175,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "plata",
    "nombre": "Plata",
    "ciudad": "Rosario",
    "lat": -33.00016,
    "lon": -60.68179,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "polledo",
    "nombre": "Polledo",
    "ciudad": "Rosario",
    "lat": -32.88445,
    "lon": -60.71865,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "portal-de-aldea",
    "nombre": "Portal de Aldea",
    "ciudad": "Rosario",
    "lat": -32.91689,
    "lon": -60.76564,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "presidente-roque-saenz-pena",
    "nombre": "Presidente Roque Saenz Peña",
    "ciudad": "Rosario",
    "lat": -33.00639,
    "lon": -60.64049,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "puente-gallego",
    "nombre": "Puente Gallego",
    "ciudad": "Rosario",
    "lat": -33.02794,
    "lon": -60.6864,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "puerto-norte",
    "nombre": "Puerto Norte",
    "ciudad": "Rosario",
    "lat": -32.92804,
    "lon": -60.66083,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "republica-de-la-sexta",
    "nombre": "Republica de la Sexta",
    "ciudad": "Rosario",
    "lat": -32.96562,
    "lon": -60.63072,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1119,
    "muestrasDepto": 1
  },
  {
    "slug": "roberto-fontanarrosa",
    "nombre": "Roberto Fontanarrosa",
    "ciudad": "Rosario",
    "lat": -32.88036,
    "lon": -60.72486,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "roque-carranza",
    "nombre": "Roque Carranza",
    "ciudad": "Rosario",
    "lat": -32.87185,
    "lon": -60.70189,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "saladillo",
    "nombre": "Saladillo",
    "ciudad": "Rosario",
    "lat": -32.99994,
    "lon": -60.62774,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "saladillo-sur",
    "nombre": "Saladillo Sur",
    "ciudad": "Rosario",
    "lat": -32.9994,
    "lon": -60.61888,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-cayetano",
    "nombre": "San Cayetano",
    "ciudad": "Rosario",
    "lat": -32.93054,
    "lon": -60.75667,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-cayetano-oeste",
    "nombre": "San Cayetano Oeste",
    "ciudad": "Rosario",
    "lat": -32.96535,
    "lon": -60.73004,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "san-eduardo",
    "nombre": "San Eduardo",
    "ciudad": "Rosario",
    "lat": -32.912,
    "lon": -60.76697,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-lucia",
    "nombre": "Santa Lucía",
    "ciudad": "Rosario",
    "lat": -32.95444,
    "lon": -60.72636,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "santa-teresita",
    "nombre": "Santa Teresita",
    "ciudad": "Rosario",
    "lat": -32.98851,
    "lon": -60.67964,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "stella-maris",
    "nombre": "Stella Maris",
    "ciudad": "Rosario",
    "lat": -32.9185,
    "lon": -60.74779,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tango",
    "nombre": "Tango",
    "ciudad": "Rosario",
    "lat": -32.94427,
    "lon": -60.75379,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tierra-nueva",
    "nombre": "Tierra Nueva",
    "ciudad": "Rosario",
    "lat": -32.9292,
    "lon": -60.76058,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": 1902,
    "muestrasDepto": 4
  },
  {
    "slug": "tio-rolo",
    "nombre": "Tio Rolo",
    "ciudad": "Rosario",
    "lat": -33.01645,
    "lon": -60.68823,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "tiro-suizo",
    "nombre": "Tiro Suizo",
    "ciudad": "Rosario",
    "lat": -32.99948,
    "lon": -60.65257,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "triangulo",
    "nombre": "Triángulo",
    "ciudad": "Rosario",
    "lat": -32.96697,
    "lon": -60.70064,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "union",
    "nombre": "Unión",
    "ciudad": "Rosario",
    "lat": -32.89689,
    "lon": -60.70421,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "union-y-parque-casas",
    "nombre": "Unión y Parque Casas",
    "ciudad": "Rosario",
    "lat": -32.90134,
    "lon": -60.70284,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "vicente-lopez-y-planes",
    "nombre": "Vicente Lopez y Planes",
    "ciudad": "Rosario",
    "lat": -33.01153,
    "lon": -60.64566,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "victoria-walsh",
    "nombre": "Victoria Walsh",
    "ciudad": "Rosario",
    "lat": -32.96462,
    "lon": -60.68909,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-banana",
    "nombre": "Villa Banana",
    "ciudad": "Rosario",
    "lat": -32.95951,
    "lon": -60.69191,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-cooperativa-25-de-mayo",
    "nombre": "Villa Cooperativa 25 de Mayo",
    "ciudad": "Rosario",
    "lat": -32.89152,
    "lon": -60.73902,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-de-empalme-graneros",
    "nombre": "Villa de Empalme Graneros",
    "ciudad": "Rosario",
    "lat": -32.9125,
    "lon": -60.70576,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-la-antena",
    "nombre": "Villa La Antena",
    "ciudad": "Rosario",
    "lat": -32.94239,
    "lon": -60.74623,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-la-bombacha",
    "nombre": "Villa La Bombacha",
    "ciudad": "Rosario",
    "lat": -32.91518,
    "lon": -60.7497,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-la-lata",
    "nombre": "Villa La Lata",
    "ciudad": "Rosario",
    "lat": -32.97163,
    "lon": -60.64962,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-la-vincha",
    "nombre": "Villa La Vincha",
    "ciudad": "Rosario",
    "lat": -32.98682,
    "lon": -60.69666,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-los-euca",
    "nombre": "Villa Los Euca",
    "ciudad": "Rosario",
    "lat": -32.9506,
    "lon": -60.72384,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-manuelita",
    "nombre": "Villa Manuelita",
    "ciudad": "Rosario",
    "lat": -32.98587,
    "lon": -60.62523,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-olimpica",
    "nombre": "Villa Olímpica",
    "ciudad": "Rosario",
    "lat": -32.99244,
    "lon": -60.63961,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-puente-negro",
    "nombre": "Villa Puente Negro",
    "ciudad": "Rosario",
    "lat": -32.90645,
    "lon": -60.70538,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-santa-rosa",
    "nombre": "Villa Santa Rosa",
    "ciudad": "Rosario",
    "lat": -32.9177,
    "lon": -60.75045,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-urquiza",
    "nombre": "Villa Urquiza",
    "ciudad": "Rosario",
    "lat": -32.95485,
    "lon": -60.7043,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  },
  {
    "slug": "villa-via-honda",
    "nombre": "Villa Vía Honda",
    "ciudad": "Rosario",
    "lat": -32.97545,
    "lon": -60.69051,
    "cerrado": false,
    "ppm2": null,
    "muestras": 0,
    "ppm2Depto": null,
    "muestrasDepto": 0
  }
]

export const getBarrio = (slug: string) => BARRIOS_TASADOR.find(b => b.slug === slug)

// Precio de TIERRA efectivo (casas y lotes).
export function precioTierra(b: BarrioTasador): { ppm2: number; fuente: "curado" | "barrio" | "ciudad"; muestras: number } {
  if (b.ppm2Curado) return { ppm2: b.ppm2Curado, fuente: "curado", muestras: 0 }
  if (b.ppm2 && b.muestras > 0) return { ppm2: b.ppm2, fuente: "barrio", muestras: b.muestras }
  return { ppm2: PPM2_CIUDAD[b.ciudad] ?? 150, fuente: "ciudad", muestras: 0 }
}

// Precio por m² CUBIERTO de departamentos (método comparativo, no del costo:
// un depto no tiene lote propio, se valúa contra unidades similares de la zona).
export function precioDepto(b: BarrioTasador): { ppm2: number; fuente: "curado" | "barrio" | "ciudad"; muestras: number } {
  if (b.ppm2Depto && b.muestrasDepto > 0) return { ppm2: b.ppm2Depto, fuente: "barrio", muestras: b.muestrasDepto }
  return { ppm2: PPM2_DEPTO_CIUDAD[b.ciudad] ?? 2000, fuente: "ciudad", muestras: 0 }
}

// Lista liviana para el selector de barrio del widget: cada entrada con su
// precio YA resuelto (curado > muestra propia > paracaídas de ciudad).
export interface OpcionBarrioSelector {
  slug: string
  nombre: string
  ciudad: string
  tierra: number
  fuenteTierra: "curado" | "barrio" | "ciudad"
  muestrasTierra: number
  depto: number
  fuenteDepto: "curado" | "barrio" | "ciudad"
  muestrasDepto: number
}

export function opcionesSelector(): OpcionBarrioSelector[] {
  return BARRIOS_TASADOR.map((b) => {
    const t = precioTierra(b)
    const d = precioDepto(b)
    return {
      slug: b.slug,
      nombre: b.nombre,
      ciudad: b.ciudad,
      tierra: t.ppm2,
      fuenteTierra: t.fuente,
      muestrasTierra: t.muestras,
      depto: d.ppm2,
      fuenteDepto: d.fuente,
      muestrasDepto: d.muestras,
    }
  }).sort((a, b) =>
    a.ciudad === b.ciudad ? a.nombre.localeCompare(b.nombre, "es") : a.ciudad.localeCompare(b.ciudad, "es"),
  )
}
