import type { TemaPropuesto } from '../types';

export const TEMAS_EVERGREEN: TemaPropuesto[] = [
  {
    titulo: 'Cómo tasar correctamente una propiedad en Funes y Roldán',
    angulo_local: 'Comparables reales de operaciones cerradas en barrios del corredor oeste',
    keywords_seo: ['tasar propiedad funes', 'tasación inmobiliaria roldán', 'valor propiedad'],
    fuentes_consultar: ['Datos propios SI Inmobiliaria', 'COCIR'],
    tipo: 'guia',
    urgencia: 'baja',
    score_seo: 7,
  },
  {
    titulo: 'Diferencias entre comprar terreno en country vs barrio abierto',
    angulo_local: 'Análisis con precios reales de countries de Funes y barrios abiertos de Roldán',
    keywords_seo: ['terreno country funes', 'barrio abierto roldán', 'comprar lote'],
    fuentes_consultar: ['Zonaprop', 'Datos propios'],
    tipo: 'comparacion',
    urgencia: 'baja',
    score_seo: 7,
  },
  {
    titulo: 'Qué evaluar antes de invertir en Funes Hills',
    angulo_local: 'Zoom al barrio premium de Funes: amenities, valuación, perfil de comprador',
    keywords_seo: ['funes hills', 'invertir funes hills', 'barrio cerrado funes'],
    fuentes_consultar: ['Reporte Inmobiliario', 'Datos propios'],
    tipo: 'zoom_barrio',
    urgencia: 'baja',
    score_seo: 8,
  },
  {
    titulo: 'Costos ocultos al comprar una propiedad en el corredor oeste',
    angulo_local: 'Gastos de escrituración, comisiones, impuestos y servicios en Funes/Roldán',
    keywords_seo: ['costos comprar propiedad', 'gastos escritura funes', 'comisión inmobiliaria'],
    fuentes_consultar: ['Colegio de Escribanos Santa Fe'],
    tipo: 'guia',
    urgencia: 'baja',
    score_seo: 6,
  },
  {
    titulo: 'Crédito hipotecario UVA en 2026: realidad para Funes y Roldán',
    angulo_local: 'Qué propiedades del corredor oeste califican y cuánto se paga de cuota',
    keywords_seo: ['crédito hipotecario uva 2026', 'hipoteca funes', 'crédito vivienda roldán'],
    fuentes_consultar: ['BCRA', 'Banco Nación', 'Reporte Inmobiliario'],
    tipo: 'coyuntura',
    urgencia: 'baja',
    score_seo: 8,
  },
  {
    titulo: 'Alquilar vs comprar en Roldán: análisis con números actuales',
    angulo_local: 'Comparativa rent vs buy con valores reales del mercado roldanense',
    keywords_seo: ['alquilar o comprar roldán', 'conviene alquilar', 'precios alquiler roldán'],
    fuentes_consultar: ['Datos propios', 'Zonaprop'],
    tipo: 'comparacion',
    urgencia: 'baja',
    score_seo: 7,
  },
  {
    titulo: 'Qué mirar en una tasación profesional',
    angulo_local: 'Errores comunes al valuar propiedades en zona oeste y cómo evitarlos',
    keywords_seo: ['tasación profesional', 'valuar propiedad', 'precio justo inmueble'],
    fuentes_consultar: ['COCIR', 'Datos propios'],
    tipo: 'guia',
    urgencia: 'baja',
    score_seo: 6,
  },
  {
    titulo: 'Inversión en pozo en zona oeste: riesgos y oportunidades',
    angulo_local: 'Desarrollos actuales en Funes y Roldán, qué evaluar antes de entrar',
    keywords_seo: ['inversión en pozo funes', 'comprar en pozo roldán', 'desarrollos inmobiliarios'],
    fuentes_consultar: ['Reporte Inmobiliario', 'CAC'],
    tipo: 'tendencia',
    urgencia: 'baja',
    score_seo: 7,
  },
  {
    titulo: 'Por qué la zona oeste sigue siendo refugio de capital',
    angulo_local: 'Valorización histórica de Funes y Roldán vs Rosario centro',
    keywords_seo: ['inversión inmobiliaria funes', 'refugio de valor', 'zona oeste rosario'],
    fuentes_consultar: ['Reporte Inmobiliario', 'UNR', 'COCIR'],
    tipo: 'tendencia',
    urgencia: 'baja',
    score_seo: 6,
  },
  {
    titulo: 'Roldán hoy: barrios consolidados vs en desarrollo',
    angulo_local: 'Mapa actualizado de barrios de Roldán, precios y proyección',
    keywords_seo: ['barrios roldán', 'terrenos roldán', 'dónde comprar roldán'],
    fuentes_consultar: ['Datos propios', 'El Roldanense'],
    tipo: 'zoom_barrio',
    urgencia: 'baja',
    score_seo: 7,
  },
];
